### ISSUE TITLE
Please, can you stop realeasing new releases with the same version number of previous releases?

### ISSUE THREAD

**Issue by 4re** [sekrit-twc/zimg#10]
That basically breaks packages for source based distributions.
What's the point? If the change is worth it just release a new version with a proper version number increase, if it is not worth it just don't release anything.

I hope this message does not come as rude, but I truly can't understand the reasoning behind this.

**Comment by sekrit-twc** [comment]
When did this happen? I rewrote the commit history yesterday, but no code was changed.

**Comment by 4re** [comment]
Yesterday at ~6:20 gtm+2

This is is the second time it happens.

Hashes for all three source tarbals changed invalidating all three gentoo
packages associated with them.

Maybe every time you rewrite the commit history or something sources are
repackaged.

**Comment by sekrit-twc** [comment]
I think Github automatically creates the tarballs. Anyway, I will keep this in mind for the future.

**Comment by 4re** [comment]
Thanks :)
