### ISSUE TITLE
Scaling in RGB linear

### ISSUE THREAD

**Issue by TbtBI** [sekrit-twc/zimg#101]
Hi.

I used VapourSynth to scale a YUV420P8 video in RGB linear but I got a strange result.
```
import vapoursynth as vs
from vapoursynth import core
video = core.ffms2.Source(source=r"source.mkv")
video = core.resize.Spline36(clip=video,format=vs.RGBS, range_in_s="limited", matrix_in_s="709", primaries_in_s="709", primaries_s="709", transfer_in_s="709", transfer_s="linear",matrix_s="rgb",range_s="limited",dither_type="none")
video = core.resize.Spline36(clip=video,width=854, height=356, format=vs.YUV420P8, range_in_s="limited", matrix_in_s="rgb", primaries_in_s="709", primaries_s="709", transfer_in_s="linear", transfer_s="709",matrix_s="709",range_s="limited",dither_type="error_diffusion")
video.set_output()
```
The result - http://imgbox.com/2FiQgCKD

Scale with Avisynth dither in RGB linear:
```
FFVideoSource("source.mkv")
dither_convert_yuv_to_rgb(output="rgb48y",chromak="spline36",matrix="709",lsb_in=false)
dither_y_gamma_to_linear(false, false, "709")
dither_resize16(854,356)
dither_y_linear_to_gamma(false, false, "709")
dither_convert_rgb_to_yuv(selectevery(3,0),selectevery(3,1),selectevery(3,2),chromak="spline36",matrix="709",lsb=true)
f3kdb(0,0,0,0,0,0, keep_tv_range=true, input_depth=16,output_depth=8)
```
The result - http://imgbox.com/o3rMdLeG

You can notice the edges difference.  Is this result expected? Could zimg scaling be used in RGB linear?

**Comment by sekrit-twc** [comment]
Please provide a test image.

**Comment by TbtBI** [comment]
https://files.catbox.moe/tsszj7.7z

**Comment by sekrit-twc** [comment]
After reviewing the provided image, I have determined that the dark/bright halo is correct behavior. Scaling in linear light naturally results in increased haloing with filters that overshoot. You might observe the haloing growing progressively worse from billinear to bicubic and then to spline/lanczos. 

DitherTools (a.k.a. fmtconv) demonstrates the same artifacts. You are seeing a visual difference with z.lib because of differences in gamma-linear conversion. When "curve" is set to "709" in `dither_y_gamma_to_linear`, it uses the BT.709 OETF. In z.lib, when the transfer characteristics are "709", then the BT.1886 EOTF is used. This is because z.lib performs all gamma operations in display light.

**Comment by TbtBI** [comment]
Correct, using "1886" curve in dither_y_gamma_to_linear/dither_y_linear_to_gamma there is no visual difference with z.lib. I didn't realize different transfer curve is used. Just those edges look a bit unnaturally compared to curve "709" but I guess it's subjective.

Thanks for the help and your time.
Thanks for you work.
This ticket could be closed.

**Comment by damian101** [comment]
> After reviewing the provided image, I have determined that the dark/bright halo is correct behavior. Scaling in linear light naturally results in increased haloing with filters that overshoot. You might observe the haloing growing progressively worse from billinear to bicubic and then to spline/lanczos.
> 
> DitherTools (a.k.a. fmtconv) demonstrates the same artifacts. You are seeing a visual difference with z.lib because of differences in gamma-linear conversion. When "curve" is set to "709" in `dither_y_gamma_to_linear`, it uses the BT.709 OETF. In z.lib, when the transfer characteristics are "709", then the BT.1886 EOTF is used. This is because z.lib performs all gamma operations in display light.

BT.1886 just defines the corresponding EOTF to the long-used BT.709 OETF. 
The OETFs specified in BT.1886 and BT.709 are identical.
