### ISSUE TITLE
Wrong output with Ryzen

### ISSUE THREAD

**Issue by TbtBI** [sekrit-twc/zimg#102]
Hi.

Used the latest release of [Avisynth+](https://github.com/pinterf/AviSynthPlus/releases) with [avsresize](https://forum.doom9.org/showthread.php?t=173986) and [HDRTools](https://github.com/jpsdr/HDRTools). avsresize compiled with [the latest](https://github.com/sekrit-twc/zimg) zimg.
```
FFVideoSource()
z_ConvertFormat(pixel_type="RGBPS", resample_filter_uv="spline36", colorspace_op="2020:st2084:2020:l=>rgb:linear:2020:l")
z_ConvertFormat(colorspace_op="rgb:linear:2020:l=>rgb:st2084:2020:l")
ConvertRGbtoXYZ(Color=0, Outputmode=2)
ConvertXYZ_Reinhard_HDRtoSDR(exposure_x=5,contrast_x=0.9)
RGBAdjust(rg=0.95,gg=0.95,bg=0.95)
ConvertXYZtoYUV(color=2)
```
[Intel 7900x output](http://imgbox.com/5wcDR4Bh) vs [Ryzen 2700x output](http://imgbox.com/XpDjMyVx)
[Source image](http://imgbox.com/6MqCNO6X)

When avsresize is compiled from [this tree](https://github.com/sekrit-twc/zimg/tree/7ea32756812d0896b2bfe4e742e1f593fe53ef89), the output is identical from both Intel and AMD.
When avsresize is compiled from [this tree](https://github.com/sekrit-twc/zimg/tree/526f9233ef72daef46512ad4f26451675b9e17c3), the AMD output is wrong.
avsresize by default is compiled with zimg approximate_gamma = 1. When it's compiled with [the latest](https://github.com/sekrit-twc/zimg) zimg and approximate_gamma = 0, the output is identical from both Intel and AMD.
Also with ZIMG_CPU_NONE and the latest zimg the output is identical.

**Comment by sekrit-twc** [comment]
Actually, this is not specific to Zen1 processor. What is happening is that the SSE code path for transfer-function lookup does not have enough precision for HDR, because it uses uniform quantization of the LUT. This can happen on pre-AVX2 Intel CPUs too. For Zen1, we can put the code path back to AVX2 (and you can do this manually), but the problem is still not really solved.

**Comment by sekrit-twc** [comment]
Thinking about this further, is this a problem on an HDR display, or is it only apparent when viewing the ST.2084 image on a non-HDR display? This banding artifact occurs primarily in very low light levels.

**Comment by TbtBI** [comment]
non-HDR display is used.

**Comment by sekrit-twc** [comment]
I mean that the artifact you discovered might not be visible when viewing the HDR as intended. It turns out not to matter though, since I found a solution.

**Comment by TbtBI** [comment]
I don't have HDR display, so can't test what the output would be.

Anyway, the [solution](https://github.com/sekrit-twc/zimg/commit/9d148e800806ad227516e1c769a41762a00d5f51) is ok, no problems anymore.

It seems this is resolved.
Thanks.
