### ISSUE TITLE
operation_impl_sse2.cpp:27:2: error: static assertion failed: object sizes must match

### ISSUE THREAD

**Issue by kuh3h3** [sekrit-twc/zimg#103]
Maybe something wrong in https://github.com/sekrit-twc/zimg/commit/9d148e800806ad227516e1c769a41762a00d5f51 ?

src/zimg/colorspace/x86/operation_impl_sse2.cpp: In instantiation of ‘T zimg::colorspace::{anonymous}::bit_cast(const U&) [with T = float; U = long unsigned int]’:
src/zimg/colorspace/x86/operation_impl_sse2.cpp:171:37:   required from here
src/zimg/colorspace/x86/operation_impl_sse2.cpp:27:2: error: static assertion failed: object sizes must match
  static_assert(sizeof(T) == sizeof(U), "object sizes must match");
  ^~~~~~~~~~~~~
Makefile:2367: recipe for target 'src/zimg/colorspace/x86/libsse2_la-operation_impl_sse2.lo' failed
make[1]: *** [src/zimg/colorspace/x86/libsse2_la-operation_impl_sse2.lo] Error 1
make[1]: *** 끝나지 않은 작업을 기다리고 있습니다....
make[1]: 디렉터리 '/home/kuh3h3/myffmpeg/build/zimg-git' 나감
Makefile:3461: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
make[1]: 디렉터리 '/home/kuh3h3/myffmpeg/build/zimg-git' 들어감
  CXXLD    libsse.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      src/zimg/colorspace/x86/libsse2_la-operation_impl_sse2.lo
src/zimg/colorspace/x86/operation_impl_sse2.cpp: In constructor ‘zimg::colorspace::{anonymous}::ToGammaLutOperationSSE2::ToGammaLutOperationSSE2(zimg::colorspace::gamma_func, float)’:
src/zimg/colorspace/x86/operation_impl_sse2.cpp:170:13: warning: unused variable ‘half’ [-Wunused-variable]
    uint16_t half = static_cast<uint16_t>(i);
             ^~~~
src/zimg/colorspace/x86/operation_impl_sse2.cpp: In instantiation of ‘T zimg::colorspace::{anonymous}::bit_cast(const U&) [with T = float; U = long unsigned int]’:
src/zimg/colorspace/x86/operation_impl_sse2.cpp:171:37:   required from here
src/zimg/colorspace/x86/operation_impl_sse2.cpp:27:2: error: static assertion failed: object sizes must match
  static_assert(sizeof(T) == sizeof(U), "object sizes must match");
  ^~~~~~~~~~~~~
Makefile:2367: recipe for target 'src/zimg/colorspace/x86/libsse2_la-operation_impl_sse2.lo' failed
make[1]: *** [src/zimg/colorspace/x86/libsse2_la-operation_impl_sse2.lo] Error 1
make[1]: 디렉터리 '/home/kuh3h3/myffmpeg/build/zimg-git' 나감
Makefile:3461: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by sekrit-twc** [comment]
fixed
