### ISSUE TITLE
provide released tarball instead of copy of git

### ISSUE THREAD

**Issue by vtorri** [sekrit-twc/zimg#107]
Hello

could you please release tarballs with 'make distcheck'. In addition to allow users to not install autotools, it compiles and run tests, verify that uninstall removes everything and create a tarball with the given compression in AM_INIT_AUTOMAKE (gz, or better : xz)

thank you

**Comment by sekrit-twc** [comment]
Won't fix.

**Comment by vtorri** [comment]
how nice is this answer

**Comment by myrsloik** [comment]
It is verrrry nice
