### ISSUE TITLE
RGB 48LE XYZ input help

### ISSUE THREAD

**Issue by bsurprised** [sekrit-twc/zimg#108]
Hi
I don't know if this is a stupid question :-) but I'm trying to find my fastest options to convert a bitmap formatted as RGB48LE in XYZ space to RGB 709 or 2020, and hopefully a result consisting of 10 bit or higher data and/or include HDR data. 
I wonder if zimg supports that and if yes, hopefully some help on the matter.
Thank you very much.

**Comment by sekrit-twc** [comment]
zimg_image_format src_format, dst_format;
    zimg_image_format_default(&src_format, ZIMG_API_VERSION);
    zimg_image_format_default(&dst_format, ZIMG_API_VERSION);

    // Width, height here.
    src_format.pixel_type = ZIMG_PIXEL_WORD;
    src_format.color_family = ZIMG_COLOR_RGB;
    src_format.matrix_coefficients = ZIMG_MATRIX_RGB;
    src_format.transfer_characteristics = ZIMG_TRANSFER_LINEAR; // Or something else.
    src_format.color_primaries = ZIMG_PRIMARIES_ST428;

    // Width, height here.
    dst_format.pixel_type = ZIMG_PIXEL_WORD;
    dst_format.color_family = ZIMG_COLOR_RGB;
    dst_format.matrix_coefficients = ZIMG_MATRIX_RGB;
    dst_format.transfer_characteristics = ZIMG_TRANSFER_BT2020_10;
    dst_format.color_primaries = ZIMG_PRIMARIES_BT2020;

    zimg_filter_graph *graph = zimg_filter_graph_build(&src_format, &dst_format, NULL);

If the XYZ contains colors not representable in the output color space, then the colors will be per-channel c.lipped (inaccurate). To handle this case, you can convert to floating-point linear RGB and use a separate solution for gamut mapping. Note that XYZ exchange is most commonly used to transfer DCI-P3 content.

**Comment by bsurprised** [comment]
Great, thank you for the solution.
Does the api support passing the packed byte buffer, or should I convert it to planar first? I remember you once mentioned in comments that only planar input is accepted.

**Comment by sekrit-twc** [comment]
Planar only.
