### ISSUE TITLE
[MSVC] name lib conflict [zlib|z.lib] and [zimg|z.lib]

### ISSUE THREAD

**Issue by Voskrese** [sekrit-twc/zimg#112]
https://github.com/sekrit-twc/zimg/blob/master/zimg.pc.in
`Libs: -L${libdir} -lzimg` - zimg

https://github.com/Kitware/CMake/blob/2a1be178de5f12d55ec486609f4512e6b2b9d168/Modules/FindZLIB.cmake#L70
`set(ZLIB_NAMES z zlib zdll zlib1 zlibstatic)`

How to solve this problem?

**Comment by sekrit-twc** [comment]
?

**Comment by Voskrese** [comment]
library file name conflict, how else to explain?

**Comment by sekrit-twc** [comment]
The list of names you provided do not have a conflict

**Comment by Voskrese** [comment]
and the discrepancy between the output name and the name of the library name in zimg.pc

**Comment by Voskrese** [comment]
vcpkg\packages\zimg_x64-windows\lib> `ls`
`testcommon.lib  z.lib  z_imp.lib`

**Comment by Voskrese** [comment]
vcpkg\packages\zlib_x64-windows\lib> ` ls`
`pkgconfig  z.lib`

**Comment by sekrit-twc** [comment]
MSVC projects are not supported. Please use automake.

**Comment by Voskrese** [comment]
how to understand you? I just compiled the library through MSVC projects 

and I repeat
> and the discrepancy between the output name and the name of the library name in **zimg.pc**

Of course, this is your business, but I think it needs to be fixed, it’s not so difficult
generally good luck

**Comment by sekrit-twc** [comment]
There is no discrepancy if you use Automake. Cheers.

**Comment by sethk** [comment]
How about deleting the Visual Studio projects from your project if they are unsupported and generate binaries that won't link outside the project?
