### ISSUE TITLE
Little warnings

### ISSUE THREAD

**Issue by ValZapod** [sekrit-twc/zimg#115]
Just checked code. Nothing serious.
[projectafter2.txt](https://github.com/sekrit-twc/zimg/files/3840168/projectafter2.txt)

Though maybe this two are bad:
https://github.com/sekrit-twc/zimg/blob/9b5162ecea5599f72b70e4442562ef394a5d836e/src/zimg/common/x86/cpuinfo_x86.cpp#L96-L102
vnni is assigned twice, is this normal?

And all those Expression "'N >= 0' is always true. Unsigned type value is always >= 0." See file))

**Comment by sekrit-twc** [comment]
Thanks for finding this.
