### ISSUE TITLE
ICtCp (IPTPQc2) support for Dolby Vision

### ISSUE THREAD

**Issue by ValZapod** [sekrit-twc/zimg#117]
There is this file (03. Color Bars BT2020 50%_Blue Filter_Dolby_Vision.mp4) [Dolby_Vision_Test_Pattern_Demo.zip](https://github.com/sekrit-twc/zimg/files/3894102/Dolby_Vision_Test_Pattern_Demo.zip)
which has wrong colors in ffmpeg maybe because of 
1) Difference between ICtCp and ITP propitiatory of Dolby Vision (which again can be different from original ITP, so called IPTPQc2/IPT color space). https://github.com/sekrit-twc/zimg/issues/69#issuecomment-552237392 @dzung-hoang
2) ffmpeg not recognizing ICtCp (really more likely, which should be fixed then) **Here, it now recognises profile 5!**
3) Problem could be in the dolby vision enhancement layer https://trac.ffmpeg.org/ticket/5688. A.k.a. **reshaping** part.

@richardpl @sekrit-twc 

See https://trac.ffmpeg.org/ticket/7624.

Also there is a bigger example https://drive.google.com/file/d/1aP276spsqW-EbIIVrzdI9mwTYO87d0ac/view?usp=sharing from LG. (See  https://github.com/HandBrake/HandBrake/issues/1728#issuecomment-448015493) @cehoyos I think we should 

> agree on colours

 already!

Thanks.

**Comment by ValZapod** [comment]
Also see https://www.shadertoy.com/view/ldKcz3
and https://gitlab.com/standards/HDRTools/blob/master/common/src/ToneMappingBT2390IPT.cpp

**Comment by ValZapod** [comment]
https://github.com/testing-av/testing-video/blob/master/core/src/main/java/band/full/video/dolby/IPTPQc2.java
So this 💩 is called IPTPQc2/IPT color space.

**Comment by ValZapod** [comment]
We found an appx windows 10 executable that can decode dolby vision with ITP to sdr and HDR correctly, that is crazy! https://drive.google.com/file/d/1MCtZHrmPcIBwh7GjoRxVpp6VR7GvbyEY/view

**Comment by TomArrow** [comment]
Any updates on this by any chance? Came here after looking at the avsresize convertFormat code and realizing it depends on zimg. 
According to https://en.wikipedia.org/wiki/ICtCp "just" (?) a new matrix of coefficients would be necessary. That wouldn't account for the polynomial curve stuff but at least it might give correct-ish colors, which would be a great start.

**Comment by ValZapod** [comment]
> new matrix of coefficients

Unfortunately it changes on the fly, in "reshaper" process. Indeed, it is better than nothing and indeed the biggest problem here may be to account for full range. See https://code.videolan.org/videolan/libplacebo/-/issues/113

**Comment by sekrit-twc** [comment]
z.lib already supports ICtCp.

**Comment by TomArrow** [comment]
That's a bummer, but not too surprising I suppose. Could just give it some kind of "_bad_approximation" suffix for the time being. Why is the full range a problem? Sorry if I'm missing an obvious point, all I know is I can set fullrange in convertFormat (which uses zimg). Those pics in that thread in any case look a lot better than what I'm getting now.

@sekrit-twc IPTPQc2 is a variation of ICtCp. The ICtCp one that's currently implemented sadly doesn't produce anything useful.

**Comment by TomArrow** [comment]
That guy on the VLC issue posted the metadata and at least within that, the coefficients seem consistent:
ycc_to_rgb_coef0: 8192,
ycc_to_rgb_coef1: 799,
ycc_to_rgb_coef2: 1681,
ycc_to_rgb_coef3: 8192,
ycc_to_rgb_coef4: -933,
ycc_to_rgb_coef5: 1091,
ycc_to_rgb_coef6: 8192,
ycc_to_rgb_coef7: 267,
ycc_to_rgb_coef8: -5545,
ycc_to_rgb_offset0: 0,
ycc_to_rgb_offset1: 134217728,
ycc_to_rgb_offset2: 134217728,
rgb_to_lms_coef0: 17081,
rgb_to_lms_coef1: -349,
rgb_to_lms_coef2: -349,
rgb_to_lms_coef3: -349,
rgb_to_lms_coef4: 17081,
rgb_to_lms_coef5: -349,
rgb_to_lms_coef6: -349,
rgb_to_lms_coef7: -349,
rgb_to_lms_coef8: 17081,

There are 419 sets of these in the metadata and they all seem to have the same values, which seem in turn consistent with what's written in the wikipedia article.

**Comment by dwbuiten** [comment]
> which seem in turn consistent with what's written in the wikipedia article

Just to note, the Wikipedia article's reference for those numbers is an MPV bug report, in which the author of libplacebo discusses them; it's a cyclical reference.

**Comment by sekrit-twc** [comment]
z.lib implements the appropriate ITU standards as referenced in T-REC-H.265. It has fully passed validation as described in the original issue #69. No information has been provided regarding any other specification.

**Comment by ValZapod** [comment]
> Just to note, the Wikipedia article's reference for those numbers is an MPV bug report, in which the author of libplacebo discusses them; it's a cyclical reference.

It references the patent. I wrote most of the Wikipedia article. 

> coefficients seem consistent:

The reshaping is there somewhere.

**Comment by ValZapod** [comment]
> It has fully passed validation as described in the original issue

Nope. Did you read the latest comment there? I gave you interger matrixes with 100% precision as specified by https://www.itu.int/ITU-T/recommendations/rec.aspx?id=13441&lang=en

**Comment by sekrit-twc** [comment]
z.lib coefficients are exact to 15 decimal places. Please stop trolling.

https://onlinegdb.com/t2zDyC2FD

**Comment by ValZapod** [comment]
> Please stop trolling.

So integer optimisations are now called trolling? I was talking about that. Again, why not do the other matrix as specified in metadata? Are you afraid of propriatory stuff of DoVi or what?

**Comment by TomArrow** [comment]
@sekrit-twc  ICtCp is not the same as the Dolby variant though. They are two separate things, only related in that they have a similar name. I do believe you that you correctly implemented the normal one.

**Comment by sekrit-twc** [comment]
After consulting with the appropriate experts, I have determined that there is currently insufficient information to implement DOLBY VISION profiles 5/7 (RPU). I created #136 to track this.
