### ISSUE TITLE
Resize broken in GCC 9.2 compiled binaries

### ISSUE THREAD

**Issue by Chipcraft** [sekrit-twc/zimg#119]
Latest commit: [https://github.com/sekrit-twc/zimg/commit/9ae36d7d5f7420eaacd9644451933512fa13d716](url)

mingw-w64-x86_64-gcc 9.2.0-2 toolchain, zimg configured with "--enable-static" parameter.

In total four "warning: requested alignment 32 is larger than 16" are being issued, in (related?):

error_diffusion_avx2.cpp:320:30:
resize_impl_avx2.cpp:393:36
resize_impl_avx2.cpp:708:31
resize_impl_avx2.cpp:840:49

When ffmpeg is used to call zimg resize, there is no output file created.

VS 16.4.0 compiled binaries work fine.

**Comment by sekrit-twc** [comment]
Did it work previously?

**Comment by sekrit-twc** [comment]
Need more information,.
