### ISSUE TITLE
Compile problem on Linux GCC 10.1.0

### ISSUE THREAD

**Issue by rubyFeedback** [sekrit-twc/zimg#127]
Hello there:

trying to compile zimg-2.9.3 from the releases tarball fails:

I tried to do autoconf/autoreconf. Not sure if that was the right
thing to do (I think cmake and meson spoiled me so much
that I don't trust GNU configure that much anymore ...)

make[1]: Entering directory '/Depot/jjj/zimg-2.9.3'
  CXX      dummy.lo
  CXX      src/zimg/api/libzimg_internal_la-zimg.lo
  CXX      src/zimg/colorspace/libzimg_internal_la-colorspace.lo
  CXX      src/zimg/colorspace/libzimg_internal_la-colorspace_param.lo
  CXX      src/zimg/colorspace/libzimg_internal_la-gamma.lo
  CXX      src/zimg/colorspace/libzimg_internal_la-graph.lo
In file included from src/zimg/colorspace/graph.cpp:9:
src/zimg/colorspace/colorspace.h: In function ‘std::vector<std::function<std::unique_ptr<zimg::colorspace::Operation>(const zimg::colorspace::OperationParams&, zimg::CPUClass)> > zimg::colorspace::get_operation_path(const zimg::colorspace::ColorspaceDefinition&, const zimg::colorspace::ColorspaceDefinition&)’:
src/zimg/colorspace/colorspace.h:104:11: warning: ‘vertex.zimg::colorspace::ColorspaceDefinition::matrix’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  104 |  return a.matrix == b.matrix && a.transfer == b.transfer && a.primaries == b.primaries;
      |         ~~^~~~~~
  CXX      src/zimg/colorspace/libzimg_internal_la-matrix3.lo
src/zimg/colorspace/matrix3.cpp: In function ‘zimg::colorspace::Vector3 zimg::colorspace::operator*(const zimg::colorspace::Vector3&, const zimg::colorspace::Vector3&)’:
src/zimg/colorspace/matrix3.cpp:20:7: error: ‘size_t’ was not declared in this scope; did you mean ‘std::size_t’?
   20 |  for (size_t i = 0; i < 3; ++i) {
      |       ^~~~~~
      |       std::size_t
In file included from /home/Programs/Gcc/10.1.0/include/c++/10.1.0/utility:68,
                 from /home/Programs/Gcc/10.1.0/include/c++/10.1.0/array:38,
                 from src/zimg/colorspace/matrix3.h:6,
                 from src/zimg/colorspace/matrix3.cpp:1:
/home/Programs/Gcc/10.1.0/include/c++/10.1.0/x86_64-pc-linux-gnu/bits/c++config.h:260:26: note: ‘std::size_t’ declared here
  260 |   typedef __SIZE_TYPE__  size_t;
      |                          ^~~~~~
src/zimg/colorspace/matrix3.cpp:20:21: error: ‘i’ was not declared in this scope
   20 |  for (size_t i = 0; i < 3; ++i) {
      |                     ^
src/zimg/colorspace/matrix3.cpp: In function ‘zimg::colorspace::Vector3 zimg::colorspace::operator*(const zimg::colorspace::Matrix3x3&, const zimg::colorspace::Vector3&)’:
src/zimg/colorspace/matrix3.cpp:30:7: error: ‘size_t’ was not declared in this scope; did you mean ‘std::size_t’?
   30 |  for (size_t i = 0; i < 3; ++i) {
      |       ^~~~~~
      |       std::size_t
In file included from /home/Programs/Gcc/10.1.0/include/c++/10.1.0/utility:68,
                 from /home/Programs/Gcc/10.1.0/include/c++/10.1.0/array:38,
                 from src/zimg/colorspace/matrix3.h:6,
                 from src/zimg/colorspace/matrix3.cpp:1:
/home/Programs/Gcc/10.1.0/include/c++/10.1.0/x86_64-pc-linux-gnu/bits/c++config.h:260:26: note: ‘std::size_t’ declared here
  260 |   typedef __SIZE_TYPE__  size_t;
      |                          ^~~~~~
src/zimg/colorspace/matrix3.cpp:30:21: error: ‘i’ was not declared in this scope
   30 |  for (size_t i = 0; i < 3; ++i) {
      |                     ^
src/zimg/colorspace/matrix3.cpp:33:14: error: expected ‘;’ before ‘k’
   33 |   for (size_t k = 0; k < 3; ++k) {
      |              ^~
      |              ;
src/zimg/colorspace/matrix3.cpp:33:22: error: ‘k’ was not declared in this scope
   33 |   for (size_t k = 0; k < 3; ++k) {
      |                      ^
src/zimg/colorspace/matrix3.cpp: In function ‘zimg::colorspace::Matrix3x3 zimg::colorspace::operator*(const zimg::colorspace::Matrix3x3&, const zimg::colorspace::Matrix3x3&)’:
src/zimg/colorspace/matrix3.cpp:45:7: error: ‘size_t’ was not declared in this scope; did you mean ‘std::size_t’?
   45 |  for (size_t i = 0; i < 3; ++i) {
      |       ^~~~~~
      |       std::size_t
In file included from /home/Programs/Gcc/10.1.0/include/c++/10.1.0/utility:68,
                 from /home/Programs/Gcc/10.1.0/include/c++/10.1.0/array:38,
                 from src/zimg/colorspace/matrix3.h:6,
                 from src/zimg/colorspace/matrix3.cpp:1:
/home/Programs/Gcc/10.1.0/include/c++/10.1.0/x86_64-pc-linux-gnu/bits/c++config.h:260:26: note: ‘std::size_t’ declared here
  260 |   typedef __SIZE_TYPE__  size_t;
      |                          ^~~~~~
src/zimg/colorspace/matrix3.cpp:45:21: error: ‘i’ was not declared in this scope
   45 |  for (size_t i = 0; i < 3; ++i) {
      |                     ^
src/zimg/colorspace/matrix3.cpp:46:14: error: expected ‘;’ before ‘j’
   46 |   for (size_t j = 0; j < 3; ++j) {
      |              ^~
      |              ;
src/zimg/colorspace/matrix3.cpp:46:22: error: ‘j’ was not declared in this scope
   46 |   for (size_t j = 0; j < 3; ++j) {
      |                      ^
src/zimg/colorspace/matrix3.cpp:49:15: error: expected ‘;’ before ‘k’
   49 |    for (size_t k = 0; k < 3; ++k) {
      |               ^~
      |               ;
src/zimg/colorspace/matrix3.cpp:49:23: error: ‘k’ was not declared in this scope
   49 |    for (size_t k = 0; k < 3; ++k) {
      |                       ^
src/zimg/colorspace/matrix3.cpp: In function ‘zimg::colorspace::Matrix3x3 zimg::colorspace::transpose(const zimg::colorspace::Matrix3x3&)’:
src/zimg/colorspace/matrix3.cpp:101:7: error: ‘size_t’ was not declared in this scope; did you mean ‘std::size_t’?
  101 |  for (size_t i = 0; i < 3; ++i) {
      |       ^~~~~~
      |       std::size_t
In file included from /home/Programs/Gcc/10.1.0/include/c++/10.1.0/utility:68,
                 from /home/Programs/Gcc/10.1.0/include/c++/10.1.0/array:38,
                 from src/zimg/colorspace/matrix3.h:6,
                 from src/zimg/colorspace/matrix3.cpp:1:
/home/Programs/Gcc/10.1.0/include/c++/10.1.0/x86_64-pc-linux-gnu/bits/c++config.h:260:26: note: ‘std::size_t’ declared here
  260 |   typedef __SIZE_TYPE__  size_t;
      |                          ^~~~~~
src/zimg/colorspace/matrix3.cpp:101:21: error: ‘i’ was not declared in this scope
  101 |  for (size_t i = 0; i < 3; ++i) {
      |                     ^
src/zimg/colorspace/matrix3.cpp:102:14: error: expected ‘;’ before ‘j’
  102 |   for (size_t j = 0; j < 3; ++j) {
      |              ^~
      |              ;
src/zimg/colorspace/matrix3.cpp:102:22: error: ‘j’ was not declared in this scope
  102 |   for (size_t j = 0; j < 3; ++j) {
      |                      ^
make[1]: *** [Makefile:2581: src/zimg/colorspace/libzimg_internal_la-matrix3.lo] Error 1
make[1]: Leaving directory '/Depot/jjj/zimg-2.9.3'
make: *** [Makefile:3612: all-recursive] Error 1

------------------

Sorry if this has been reported already or is known. Please feel free to
close this if there is no issue. I'll try with an older gcc soon.

**Comment by sekrit-twc** [comment]
#124
