### ISSUE TITLE
Errors during install

### ISSUE THREAD

**Issue by zlockhart** [sekrit-twc/zimg#129]
pi@raspberrypi:~ $ git clone https://github.com/sekrit-twc/zimg.git ~/ffmpeg-libraries/zimg   && cd ~/ffmpeg-libraries/zimg   && sh autogen.sh   && ./configure   && make   && sudo make install
Cloning into '/home/pi/ffmpeg-libraries/zimg'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 11266 (delta 36), reused 41 (delta 34), pack-reused 11205
Receiving objects: 100% (11266/11266), 2.53 MiB | 5.23 MiB/s, done.
Resolving deltas: 100% (8267/8267), done.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:10: installing './compile'
configure.ac:10: installing './config.guess'
configure.ac:10: installing './config.sub'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert armv7l-unknown-linux-gnueabihf file names to armv7l-unknown-linux-gnueabihf format... func_convert_file_noop
checking how to convert armv7l-unknown-linux-gnueabihf file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether C++ compiler accepts -std=c++14... yes
checking whether C compiler accepts -fvisibility=hidden... yes
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking whether C compiler accepts -mfp16-format=ieee... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating zimg.pc
config.status: executing depfiles commands
config.status: executing libtool commands
make[1]: Entering directory '/home/pi/ffmpeg-libraries/zimg'
  CXX      dummy.lo
  CXX      src/zimg/api/libzimg_internal_la-zimg.lo
src/zimg/api/zimg.cpp: In function ‘zimg::CPUClass {anonymous}::translate_cpu(zimg_cpu_type_e)’:
src/zimg/api/zimg.cpp:156:5: error: ‘ZIMG_CPU_ARM_NEON_v8_1’ was not declared in this scope
   { ZIMG_CPU_ARM_NEON_v8_1, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
src/zimg/api/zimg.cpp:156:5: note: suggested alternative: ‘ZIMG_CPU_ARM_NEON_VFPv4’
   { ZIMG_CPU_ARM_NEON_v8_1, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
     ZIMG_CPU_ARM_NEON_VFPv4
src/zimg/api/zimg.cpp:157:5: error: ‘ZIMG_CPU_ARM_NEON_v8_2’ was not declared in this scope
   { ZIMG_CPU_ARM_NEON_v8_2, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
src/zimg/api/zimg.cpp:157:5: note: suggested alternative: ‘ZIMG_CPU_ARM_NEON_VFPv4’
   { ZIMG_CPU_ARM_NEON_v8_2, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
     ZIMG_CPU_ARM_NEON_VFPv4
src/zimg/api/zimg.cpp:158:5: error: ‘ZIMG_CPU_ARM_NEON_v8_3’ was not declared in this scope
   { ZIMG_CPU_ARM_NEON_v8_3, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
src/zimg/api/zimg.cpp:158:5: note: suggested alternative: ‘ZIMG_CPU_ARM_NEON_VFPv3’
   { ZIMG_CPU_ARM_NEON_v8_3, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
     ZIMG_CPU_ARM_NEON_VFPv3
src/zimg/api/zimg.cpp:159:5: error: ‘ZIMG_CPU_ARM_NEON_v8_4’ was not declared in this scope
   { ZIMG_CPU_ARM_NEON_v8_4, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
src/zimg/api/zimg.cpp:159:5: note: suggested alternative: ‘ZIMG_CPU_ARM_NEON_VFPv4’
   { ZIMG_CPU_ARM_NEON_v8_4, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
     ZIMG_CPU_ARM_NEON_VFPv4
src/zimg/api/zimg.cpp:160:5: error: ‘ZIMG_CPU_ARM_NEON_v8_5’ was not declared in this scope
   { ZIMG_CPU_ARM_NEON_v8_5, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
src/zimg/api/zimg.cpp:160:5: note: suggested alternative: ‘ZIMG_CPU_ARM_NEON_VFPv4’
   { ZIMG_CPU_ARM_NEON_v8_5, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
     ZIMG_CPU_ARM_NEON_VFPv4
src/zimg/api/zimg.cpp:161:5: error: ‘ZIMG_CPU_ARM_NEON_v8_6’ was not declared in this scope
   { ZIMG_CPU_ARM_NEON_v8_6, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
src/zimg/api/zimg.cpp:161:5: note: suggested alternative: ‘ZIMG_CPU_ARM_NEON_VFPv4’
   { ZIMG_CPU_ARM_NEON_v8_6, CPUClass::ARM_NEON },
     ^~~~~~~~~~~~~~~~~~~~~~
     ZIMG_CPU_ARM_NEON_VFPv4
src/zimg/api/zimg.cpp:163:2: error: no matching function for call to ‘zimg::static_map<zimg_cpu_type_e, zimg::CPUClass, 19>::static_map(<brace-enclosed initializer list>)’
  };
  ^
In file included from src/zimg/api/zimg.cpp:11:
./src/zimg/common/static_map.h:206:17: note: candidate: ‘constexpr zimg::static_map<Key, T, N, Compare>::static_map(std::initializer_list<std::pair<const Key, T> >, Compare) [with Key = zimg_cpu_type_e; T = zimg::CPUClass; unsigned int N = 19; Compare = std::less<zimg_cpu_type_e>]’
 SM_CONSTEXPR_14 static_map<Key, T, N, Compare>::static_map(std::initializer_list<value_type> init, Compare comp) :
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/zimg/common/static_map.h:206:17: note:   candidate expects 2 arguments, 11 provided
src/zimg/api/zimg.cpp:163:2: error: could not convert ‘{{ZIMG_CPU_NONE, NONE}, {ZIMG_CPU_AUTO, AUTO}, {ZIMG_CPU_AUTO_64B, AUTO_64B}, {ZIMG_CPU_ARM_NEON_VFPv3, NONE}, {ZIMG_CPU_ARM_NEON_VFPv4, ARM_NEON}, {<expression error>, ARM_NEON}, {<expression error>, ARM_NEON}, {<expression error>, ARM_NEON}, {<expression error>, ARM_NEON}, {<expression error>, ARM_NEON}, {<expression error>, ARM_NEON}}’ from ‘<brace-enclosed initializer list>’ to ‘const zimg::static_map<zimg_cpu_type_e, zimg::CPUClass, 19>’
  };
  ^
make[1]: *** [Makefile:2953: src/zimg/api/libzimg_internal_la-zimg.lo] Error 1
make[1]: Leaving directory '/home/pi/ffmpeg-libraries/zimg'
make: *** [Makefile:4142: all-recursive] Error 1

**Comment by sekrit-twc** [comment]
Try again.

**Comment by zlockhart** [comment]
I still get the same thing.

**Comment by sekrit-twc** [comment]
Fixed.
