### ISSUE TITLE
Performance against other libraries  ?

### ISSUE THREAD

**Issue by MaximumProgrammer** [sekrit-twc/zimg#131]
Are there any Benchmarks against OpenCV or Libyuv for the most commo operations ? 

Image transformation, color conversation and so on ?

**Comment by sekrit-twc** [comment]
See Readme.RST

**Comment by richardpl** [comment]
That one compares to obsolete swscale only.

**Comment by sekrit-twc** [comment]
All swscales are obsolete.

**Comment by richardpl** [comment]
Nope, also compares only with old swscale are invalid.

**Comment by MaximumProgrammer** [comment]
It doesn't really matter i would be nice to have some benchmarks, to compare this library against other. I guess libvips is really fast about 5 - 10 times faster than OpenCV as far as i know and also checked it, which is quite fast.

**Comment by sekrit-twc** [comment]
I don't know about other libraries, but there are performance measurements in the README.


> Time (ms) to resize FHD image to UHD with Lanczos filter.
> 
> |                                | z.lib 2.8 | swscale 4.0.2* |
> |--------------------------------|-----------|----------------|
> | Intel(R) Core(TM) i7-8565U     |       7.7 |           15.2 |
> | Intel(R) Xeon(R) Platinum 8176 |      10.8 |           22.2 |
> 
> Time (ms) to convert FHD BT.709 (YUV) to FHD BT.2020.
> 
> |                                | z.lib 2.8 | swscale 4.0.2** |
> |--------------------------------|-----------|-----------------|
> | Intel(R) Core(TM) i7-8565U     |       8.3 |            17.5 |
> | Intel(R) Xeon(R) Platinum 8176 |      11.5 |            25.6 |
> 
> \* `scale=3840:2160:sws_flags=lanczos+accurate_rnd:sws_dither=none`
> 
> \** `colorspace=all=bt2020:iall=bt709:format=yuv420p10`

If you invert the processing time, you can see that a laptop-class processor can operate in excess of 100 fps per core.
