### ISSUE TITLE
regression in hlg->pq conversion from a 422 buffer

### ISSUE THREAD

**Issue by kodabb** [sekrit-twc/zimg#132]
Hi,
I tried to perform a conversion from HLG to PQ of a video frame in YUV422 and 10 bitdepth, but zimg would output all black.

I ran some more tests, and this seems to exclusively happen on 422 material, at 10 or 8 bit, and only if the input transfer is HLG. If I set any other transfer or use any other buffer size (420 or 444) this does not happen.

I bisected for a bit and I noticed that it was introduced in 3a66174df5ba24f8f3914dbf0866a2c54d651e3b, any prior hash produces the expected result.

**Comment by sekrit-twc** [comment]
Fixed in fc7473d. The issue can be worked around by explicitly setting nominal_peak_luminance.

**Comment by kodabb** [comment]
Thanks for the quick fix! Is `100.0` the value you'd need to set `nominal_peak_luminance` for HLG?

**Comment by sekrit-twc** [comment]
Yes, 100.0 is the intended default.
