### ISSUE TITLE
TV range with float

### ISSUE THREAD

**Issue by TbtBI** [sekrit-twc/zimg#134]
Hi,
This
```
clip = core.std.BlankClip(format=vs.RGB24, color=[0,0,0])
clip = core.resize.Spline36(clip, format=vs.YUV444PS, matrix_in_s="rgb", matrix_s="709")
```
gives PlaneStatsMax/Min: 0.0. If YUV444P16 is used instead of float the value is 4096. Why float doesn't return TV range for YUV?

**Comment by sekrit-twc** [comment]
Float is 0-1.

**Comment by TbtBI** [comment]
Then I guess AviSynth+ is doing wrongly such conversations because the result of the equivalent operation with AviSynth+ returns 16 / 255?
