### ISSUE TITLE
NEON on Apple silicon

### ISSUE THREAD

**Issue by galad87** [sekrit-twc/zimg#135]
Apple uses "arm64" instead of "aarch64", so the NEON files are not built by default when targeting this platform. When I manually set host to "aarch64-apple-darwin" the optimisations are built.

**Comment by galad87** [comment]
But with neon optimisations the actual output is garbled. I'll investigate and report back.

**Comment by sekrit-twc** [comment]
You can run the unit tests to pinpoint which kernel is broken.

**Comment by galad87** [comment]
Test passes.

But when I use FFmpeg filter graph with the following filters with hdr10 input:
zscale='width=1280:height=720',zscale='transfer=linear:npl=100',format='pix_fmts=gbrpf32le',tonemap='tonemap=hable:desat=0',zscale='primaries=bt2020:transfer=2020_10:matrix=bt2020nc',format='pix_fmts=yuv420p10le

or even simpler, with a bt709 input:
zscale='primaries=bt2020:transfer=2020_10:matrix=bt2020nc',format='pix_fmts=yuv420p

The output is something like 
<img width="1392" alt="Screenshot 2020-11-26 at 10 54 43" src="https://user-images.githubusercontent.com/4305519/100336085-06e35280-2fd6-11eb-85cd-fc7ac6a1e92f.png">

when NEON simd is enabled. I pinpointed it to the colourspace conversion.

Here's the build + test log: https://gist.github.com/galad87/c33a644713c303a5043de5bd12529239

**Comment by sekrit-twc** [comment]
Use testapp.exe with the "colorspace" subapp.

**Comment by sekrit-twc** [comment]
Unable to reproduce this on AMZN ARM. Command:

    ffmpeg -ss 00:30 -i LG_Chess_HDR-noaudio.mp4 -vf zscale='primaries=bt709:transfer=bt709:matrix=bt709',format='yuv420p' -frames 1 out.png

**Comment by galad87** [comment]
I can reproduce the issue in FFmpeg 4.3.1 with same argument you used but not with testapp.exe (but I might be doing something different in testapp.exe).

One of primaries, transfer, matrix is enough to trigger the issue.

I'll try a recent FFmpeg snapshot next.

**Comment by sekrit-twc** [comment]
I glanced at FFmpeg revision history and there have been no changes to vf_zscale.c since 4.3.1. As for how to use colorspaceapp, the equivalent command line is this:

    testapp colorspace --lut --cpu neon bmp@in.bmp bmp@out.bmp rgb:709:2020 rgb:709:709

**Comment by galad87** [comment]
testapp still shows no issue.
What are the correct argument to use a yuv 420 frame in testapp?

I tried to export a frame from FFmpeg:

`
ffmpeg -ss 00:05 -i input.mp4  -frames 1 in.yuv
`

and then

`
testapp colorspace --lut --cpu neon --width 1280 --height 720 yv12@in2.yuv yv12@out.yuv 709:709:2020 709:709:709
`

but it outputs a "incompatible subsampling in format" message.

Anyway, all I can do is offer remote access to a macOS arm computer if someone is interesting to debug this further.

**Comment by sekrit-twc** [comment]
colorspaceapp doesn't execute a complete filtergraph. It only accepts 4:4:4 inputs. Can the issue be reproduced in FFmpeg with 4:4:4/RGB formats?

**Comment by sekrit-twc** [comment]
@galad87

Can you provide remote access to the Apple A14/M1?

**Comment by ValZapod** [comment]
Where did I see that? Ah, yeah, here: https://trac.ffmpeg.org/ticket/9077#comment:5

That looks like the same artifact https://dev-files.blender.org/file/data/2ubaxhcrkusf6udvddh6/PHID-FILE-7izlml2yionqysqn4gma/ffmpeg-out.png, except here green colour comes from YCbCr.

**Comment by galad87** [comment]
I'm afraid I don't have access to a M1 Mac anymore.
I can rent a M1 on scaleway.com and give you access, it seems cheep enough.

**Comment by sekrit-twc** [comment]
Thanks for pointing out scaleway.com. I will investigate this service.

**Comment by galad87** [comment]
I have access to a M1 Mac again, how can I contact you to give the credentials?

**Comment by sekrit-twc** [comment]
Hi galad87, I have created a private repo to discuss this. It would help if you provide access to an environment where you have already reproduced the issue.

**Comment by sekrit-twc** [comment]
Reproduced the issue:

    ./configure --enable-testapp --host=aarch64-apple-darwin 
    zimg/testapp depth -w 3840 -h 2160 --cpu=auto i420w@test.yuv i420@test2.yuv word:l:10 byte:l:8

**Comment by sekrit-twc** [comment]
Narrowed it down further:

    zimg/testapp depth -w 3840 -h 2160 --cpu=auto i420s@test2.yuv i420@test3.yuv float byte:l:8

Float-to-integer dithering. Need to investigate the disassembly.

**Comment by sekrit-twc** [comment]
Fixed.
