### ISSUE TITLE
testapp --peak-luminance option seems to have no effect

### ISSUE THREAD

**Issue by li-zhi** [sekrit-twc/zimg#137]
I'm testing with the following testapp cmds:

```
./testapp colorspace --width 192 --height 108 --fullrange-in --fullrange-out --peak-luminance 10000 rgbpw@SCD_192x108.rgb48.plr.rgb i444w@SCD_192x108.rgb48.plr.pl10000.yuv rgb:st_2084:dcip3_d65 ictcp:st_2084:2020

./testapp colorspace --width 192 --height 108 --fullrange-in --fullrange-out --peak-luminance 1 rgbpw@SCD_192x108.rgb48.plr.rgb i444w@SCD_192x108.rgb48.plr.pl1.yuv rgb:st_2084:dcip3_d65 ictcp:st_2084:2020
```

The output videos `SCD_192x108.rgb48.plr.pl10000.yuv` and `SCD_192x108.rgb48.plr.pl1.yuv` are almost identical (with PSNR inf, 126.944 and 121.172 for the three channels).

The --peak-luminance seems to have no effect. Have I misinterpreted the meaning of the option?

This also seems to be the case in ffmpeg zscale filter (I assume the corresponding flag is `npl`).

The input video can be found here:
https://drive.google.com/file/d/1Jy-mOtucAZUXrtIAGmBFKIJ_337t4YnE/view?usp=sharing

**Comment by sekrit-twc** [comment]
`--peak-luminance` is only for SDR<-->HDR conversions. It maps the relative 1.0 luminance of SDR to a specific code value in PQ.

**Comment by li-zhi** [comment]
Make sense. Thanks!
