### ISSUE TITLE
Mismatch of testapp and ffmpeg/zscale results

### ISSUE THREAD

**Issue by li-zhi** [sekrit-twc/zimg#138]
I'm comparing the outputs of colorspace conversoin using testapp vs. ffmpeg/zscale:
```
./testapp colorspace --width 192 --height 108 --fullrange-in --fullrange-out --peak-luminance 10000 \
rgbpw@SCD_192x108.rgb48.plr.rgb \
i444w@SCD_192x108.rgb48.plr.testapp.yuv \
rgb:st_2084:2020 \
ictcp:st_2084:2020

./ffmpeg -f rawvideo -pix_fmt rgb48le -s:v 192x108 -i SCD_192x108.rgb48.rgb -vf zscale=rangein=full:range=full:npl=10000:matrixin=input:transferin=smpte2084:primariesin=2020:matrix=ictcp:transfer=smpte2084:primaries=2020,format=yuv444p16le -f rawvideo SCD_192x108.rgb48.plr.ffmpeg.yuv
```

The two commands above produce somewhat mismatched results (PSNR 72.192, 60.994, 55.346 for the three channels). Visual inspection suggests that the ffmpeg/zscale result has blockiness, potentially due to poor resampling: 
![image](https://user-images.githubusercontent.com/17128080/103571066-1a0ffa80-4e7f-11eb-8c81-085703e7888c.png)
(left hand side is ffmpeg/zscale; right hand side is testapp)

I also tried to specify `filter` or `dither` flag in ffmpeg/zscale, but neither seem to have any effect.

Does anyone have an explanation on this?

The input videos can be found in the link below:
https://drive.google.com/drive/folders/1Ia_y-IgSYDU_raLnFO7SJyoESEf_wlhg?usp=sharing

The output videos can be found below:
https://drive.google.com/drive/folders/1wpc4p_7s3gBm0XsvWM2xb712y_UoakJa?usp=sharing

**Comment by sekrit-twc** [comment]
The difference is that FFmpeg uses a LUT approximation for the gamma function (`--lut` in testapp). Are these artifacts visible when the image is viewed on an HDR monitor?

**Comment by li-zhi** [comment]
[SCD_192x108.zip](https://github.com/sekrit-twc/zimg/files/5768117/SCD_192x108.zip)

Ok. Try these input files.

I tested ffmpeg with agamma off:
```
./ffmpeg -f rawvideo -pix_fmt rgb48le -s:v 192x108 -i SCD_192x108.rgb48.rgb -vf zscale=agamma=0:rangein=full:range=full:npl=10000:matrixin=input:transferin=smpte2084:primariesin=2020:matrix=ictcp:transfer=smpte2084:primaries=2020,format=yuv444p16le -f rawvideo SCD_192x108.rgb48.plr.ffmpeg.yuv
```
It gives slightly different result but the blocky artifact persists.

I haven't tried it on a HDR display yet.

**Comment by li-zhi** [comment]
I couldn't see the same artifact from the images you have generated. (btw, I was using a tool called vooya to visualize and calculate PSNR, and the reason why you saw a different color is that i set the colorspace wrong. Below you can see the comparison side by side (left: testapp, right: ffmpeg) viewed as 709:
![image](https://user-images.githubusercontent.com/17128080/103688298-7a1da400-4f46-11eb-8800-3b2e4a9c2558.png)

Could this be an ffmpeg-only issue? Are we guaranteed that ffmpeg is using exactly the same code path as testapp?

**Comment by sekrit-twc** [comment]
I will investigate the FFmpeg code next. They should be exercising the same code, but there may be some auto-inserted swscale steps causing the issue.

**Comment by sekrit-twc** [comment]
I found that there are auto-inserted swscale steps when using format `rgb48le`. Can you reproduce with `gbrp16le`?

**Comment by li-zhi** [comment]
I ran your first command:
```
./ffmpeg -v debug -f rawvideo -pix_fmt rgb48le -s:v 192x108 -i SCD_192x108.rgb48.rgb -vf format=gbrp16le,zscale=rangein=full:range=full:npl=10000:matrixin=input:transferin=smpte2084:primariesin=2020:matrix=ictcp:transfer=smpte2084:primaries=2020,format=yuv444p16le -f rawvideo FFMPEG_ICTCP_SCD_192x108.rgb48.plr.ffmpeg.yuv
```
and I can reproduce the artifacts:
![image](https://user-images.githubusercontent.com/17128080/103712034-a4368c80-4f6d-11eb-9eb6-f120e4f8cb1e.png)

Were you saying you couldn't, and this is a build issue?

**Comment by sekrit-twc** [comment]
Please share your workflow to visualize the image. I used the provided commands to render the result back to RGB24 with FFmpeg.

**Comment by li-zhi** [comment]
After the first step to generate `FFMPEG_ICTCP_SCD_192x108.rgb48.plr.ffmpeg.yuv`, I use the "vooya" player to visualize it, which you can download from here:
https://www.offminor.de/

Display setting is as follows:
![image](https://user-images.githubusercontent.com/17128080/103715247-f929d100-4f74-11eb-840e-00766d02026b.png)

I also tried your three steps to generate the final .bmp file. It seems that the blockiness got washed out after the second step, making it much less visible in the .bmp.

**Comment by sekrit-twc** [comment]
If the image is in the ICtCp space, why do you visualise it as Rec.709? I can indeed reproduce the artifacts in the VOOYA application with your settings, but this visualisation does not represent the actual data. I tried setting VOOYA to ICtCp space, but it just produces a blank screen.

**Comment by li-zhi** [comment]
I don't trust vooya' ICtCp visualization, so I didn't even try that.

But the key point is, if you just treat the videos as 709 Y'Cb'Cr', the
content is still visually meaningful. And in this setting, if you compare
the two videos (one produced by testapp and one by ffmpeg) there is a
clearly numerical difference in the values. I am wondering why that
happens. You mentioned that it may be because of auto-inserted swscale
steps. I curious if this can be avoided.

**Comment by li-zhi** [comment]
Ah. Didn't see your EDIT section from the email thread. This explains it! Now I know how to avoid this. Thanks for digging!

**Comment by li-zhi** [comment]
Quick follow-up: do you know why swscale introduces the artifacts for rgb48le-gbrp16le conversion? This looks crappy as it's just bit re-arrangement.

What tool did you use to do the conversion? Does zscale offer a repalcement for this conversion?

**Comment by dwbuiten** [comment]
Without looking, I would not be surprised if FFmpeg roundtrips to YCbCr silently when converting between the two (it's happened before...).

As for packing/unpacking, there is libp2p (https://github.com/sekrit-twc/libp2p) among others.

**Comment by sekrit-twc** [comment]
Without knowing more about swscale, I suspect it is because there is no special-case "unscaled conversion" (sws_unscaled.c?) for rgb48/gbrp16.  I created the GBRP image by using `dd`. Unfortunately, there is probably no workaround in FFmpeg without fixing the underlying code.

**Comment by ValZapod** [comment]
> FFmpeg roundtrips to YCbCr silently when converting between the two

Oh, there are at least two open issues about that in ffmpeg: https://trac.ffmpeg.org/ticket/3345 yuv 10 bit to 8 bit 

https://trac.ffmpeg.org/ticket/979 Infamous bgr24->yuv issue that is not present when you do rgb24->yuv (yes, LOL, rgb to bgr is lossless). Can be that second one.

**Comment by ValZapod** [comment]
You need to use :format=yuvxxxx not ,format=yuv4xxxxx, okay, see https://trac.ffmpeg.org/timeline?from=2019-11-29T12%3A35%3A22%2B02%3A00&precision=second
