### ISSUE TITLE
Error when building on armv7hl

### ISSUE THREAD

**Issue by scaronni** [sekrit-twc/zimg#140]
Fedora builds are failing for `armv7hl`, as it seems Neon is always enforced.

I've tried disabling NEON_CFLAGS:

```
diff -Naur zimg-release-3.0.1.old/configure.ac zimg-release-3.0.1/configure.ac
--- zimg-release-3.0.1.old/configure.ac	2021-01-06 11:56:42.968964240 +0100
+++ zimg-release-3.0.1/configure.ac	2021-01-06 12:19:37.997535978 +0100
@@ -64,10 +64,7 @@
 X86="no"
 
 AS_CASE([$host_cpu],
-        [armv7*],  [
-                      BITS="32" ARM="yes" NEON_CFLAGS="-march=armv7-a -mfpu=neon-vfpv4"
-                      AX_CHECK_COMPILE_FLAG([-mfp16-format=ieee], [NEON_CFLAGS="$NEON_CFLAGS -mfp16-format=ieee"])
-                   ],
+        [armv7*],  [BITS="32" ARM="yes"],
         [aarch64], [BITS="64" ARM="yes"],
         [i?86],    [BITS="32" X86="yes"],
         [x86_64],  [BITS="64" X86="yes"])
```
and made sure `-mfpu` is not set in the default compiler options, but this does not seem to help, it always fails when trying to build `libneon_la-depth_convert_neon.o`.

Not my domain of expertise here, so I'm not sure I'm doing the correct thing. Is there a way to make sure Neon can be disabled at configure time? Previous release 2.9.3 built fine without touching compiler options or anything.

Thanks.

**Comment by sekrit-twc** [comment]
NEON compiler is required...

**Comment by scaronni** [comment]
So nothing has changed compared to the time 2.9.3 was built (nothing meaning no big compiler changes, etc), but 3.0.1 does not compile anymore on `armv7hl`. Full build log with compiler flags etc is here:

https://kojipkgs.fedoraproject.org//work/tasks/6113/58786113/build.log

All the other architectures are fine:

https://koji.fedoraproject.org/koji/taskinfo?taskID=58785830

**Comment by sekrit-twc** [comment]
Just use NEON. Why is this so hard?

**Comment by scaronni** [comment]
Neon is enabled by default, but on 32 bit is failing with these kind of messages with GCC 10:
```
error: inlining failed in call to 'always_inline' 'void vst1q_u8(uint8_t*, uint8x16_t)': target specific option mismatch
error: inlining failed in call to 'always_inline' 'uint8x16_t vorrq_u8(uint8x16_t, uint8x16_t)': target specific option mismatch
error: inlining failed in call to 'always_inline' 'uint8x16_t vandq_u8(uint8x16_t, uint8x16_t)': target specific option mismatch
error: inlining failed in call to 'always_inline' 'uint8x16_t vbicq_u8(uint8x16_t, uint8x16_t)': target specific option mismatch
error: inlining failed in call to 'always_inline' 'uint8x16_t vld1q_u8(const uint8_t*)': target specific option mismatch
error: inlining failed in call to 'always_inline' 'uint8x16_t vld1q_u8(const uint8_t*)': target specific option mismatch
```

**Comment by scaronni** [comment]
Builds fine for aarch64.

**Comment by sekrit-twc** [comment]
Works fine on Ubuntu.

**Comment by sekrit-twc** [comment]
Inspecting the logs reveals that your build system is broken:

libtool: compile:  g++ -DPACKAGE_NAME=\"zimg\" -DPACKAGE_TARNAME=\"zimg\" -DPACKAGE_VERSION=\"3.0.1\" "-DPACKAGE_STRING=\"zimg 3.0.1\"" -DPACKAGE_BUGREPORT=\"https://github.com/sekrit-twc/zimg/pulls\" -DPACKAGE_URL=\"https://github.com/sekrit-twc/zimg\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PTHREAD_PRIO_INHERIT=1 -DHAVE_PTHREAD=1 -DZIMG_ARM=1 -I. -I./src/zimg -std=c++14 -O2 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -DNDEBUG **-march=armv7-a -mfpu=neon-vfpv4 -mfp16-format=ieee** -fvisibility=hidden -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=armv7-a **-mfpu=vfpv3-d16** -mtune=generic-armv7-a -mabi=aapcs-linux -mfloat-abi=hard -c src/zimg/colorspace/arm/operation_impl_neon.cpp  -fPIC -DPIC -o src/zimg/colorspace/arm/.libs/libneon_la-operation_impl_neon.o

You have overridden the required CFLAGS with your shitty version.
