### ISSUE TITLE
How does zscale work under the hood?

### ISSUE THREAD

**Issue by li-zhi** [sekrit-twc/zimg#141]
I am trying to develop a deeper understanding of how zscale works under the hood. The two examples below can best explain what I am trying to understand.

1) Suppose I want to do colorspace conversion from (gbrp, PQ, P3D65) to (ICtCp, PQ, 2020). Example ffmpeg filter command would look like:
```
zscale=matrixin=gbrp:transferin=smpte2084:primariesin=smpte432:matrix=ictcp:transfer=smpte2084:primaries=2020
```
Here is what I imagine would happen under the hood: a) the R, G, B channels get transfered to linear (PQ-EOTF), followed by b) conversion from RGB with P3D65 primaries to XYZ. From there, c) XYZ got transformed to LMS, d) then PQ-OETF, e) then ICtCp. Is my understanding of the steps correct?

2) Now, besides the color space conversion, we add in scaling. For example, downscaling from 1080p to 540p:
```
zscale=960:540:filter=bilinear:matrixin=gbrp:transferin=smpte2084:primariesin=smpte432:matrix=ictcp:transfer=smpte2084:primaries=2020
```
My best guess is that the downscaling takes place in the linear domain, between step b) and c) as mentioned above. Is my guess correct?

**Comment by sekrit-twc** [comment]
(1) See src/colorspace/graph.cpp for colorspace conversion strategy. Your interpretation is correct.
(2) Scaling happens as either the first or last step, depending on which would minimize the number of pixels processed. To scale in the linear domain, two separate z.lib calls should be made.

**Comment by li-zhi** [comment]
Thanks for the pointers. Will read in detail.

On question (2): 
"Scaling happens as either the first or last step, depending on which would minimize the number of pixels processed"
-> so in the example above, the downscaling happens in the first step, since after downscaling, the rest of pipe only needs to process less pixels. Is this right?

"To scale in the linear domain, two separate z.lib calls should be made."
-> I would imagine the following will work?
```
zscale=matrixin=gbrp:transferin=smpte2084:primariesin=smpte432: \
matrix=gbrp:transfer=linear:primaries=smpte432, \
zscale=960:540:filter=bilinear:matrixin=input:transferin=input: \
primariesin=input:matrix=ictcp:transfer=smpte2084:primaries=2020
```

**Comment by sekrit-twc** [comment]
When downsampling, the resizing step happens before the colorspace step, and the proposed workflow for linear-light downsampling is correct. If the image were to be upsampled, resizing would happen after colorspace conversion, and the sequence of calls to achieve linear-light scaling would be reversed.

**Comment by li-zhi** [comment]
Thanks for the answers!
