### ISSUE TITLE
Doubt about frame-based

### ISSUE THREAD

**Issue by Kuronoe-Ookami** [sekrit-twc/zimg#146]
Hello, I am having an error when using the z_Convert Format: "clip must be frame-based". I tried to solve it in the ways I know, but it didn't work. Here is the script I am using:

##src
DGDecode_mpeg2source("C:\Anime\Encoder\Anime01.d2v", info=3)
##matrix
ColorMatrix(hints=true)
##Deinterlace
AnimeIVTC(mode=1)
##crop
crop(4, 0, -4, -0)
nnedi3_rpow2(rfactor=2, nsize=4, nns=3, qual=1, etype=0, pscrn=2, cshift="Spline36Resize", fapprox=0)
z_ConvertFormat(width=960, height=720, resample_filter ="Spline36", colorspace_op="470bg:601:470bg:f=>709:709:709:f", dither_type="none")
#fin

Any suggestion?
Thanks.

**Comment by sekrit-twc** [comment]
AssumeFrameBased()?

**Comment by Kuronoe-Ookami** [comment]
Yes, it was the first thing I tried.
Even if I remove all filters and leave only the input video, the error persists. 

In a test with the AI-upscale filter the error disappears, but I can't use this one, as this filter is slow.
Like this:
AiUpscale(Factor=2, Luma="HQ Sharp", Chroma="Spline36", mode="LineArt")
z_ConvertFormat(width=1440, height=1080, resample_filter ="Spline36", colorspace_op="470bg:601:470bg:f=>709:709:709:f", dither_type="none")

**Comment by sekrit-twc** [comment]
So

````
Source()
AssumeFrameBased()
z_ConvertFormat()
````

doesn't work?

**Comment by sekrit-twc** [comment]
Closed for no update
