### ISSUE TITLE
Demo for yuv upsampling/downsampling

### ISSUE THREAD

**Issue by suz53** [sekrit-twc/zimg#147]
I was trying to upsample a input_480x272_yuv420p.yuv file to an output_1280x720_yuv444p.yuv file.
The command line `$ ./testapp resize -w 480 -h 272 --sub-width 2 --sub-height 1 --format byte:fc ./input_480x272_yuv420p.yuv ./output_1280x720_yuv444p.yuv 1280 720` failed with error info: `bad file size`.

Could you please provide a working command line (as well as an input.yuv file maybe)? Thanks!

**Comment by sekrit-twc** [comment]
You need to provide the protocol for raw images: `i420@path.yuv`

**Comment by suz53** [comment]
Thank you for your help!

I've tried this command: `$ ./testapp unresize -w 480 -h 272 --sub-width 2 --sub-height 1 --format byte:fc i420@input_480x272_yuv420p.yuv i444@output_1280x720_yuv444p.yuv 1280 720` but still got the same `bad file size` error. 

If you could provide a working demo, that would be great and helpful to better understand the resize/unresize module. Thanks again!

**Comment by sekrit-twc** [comment]
1. `--sub-width/--sub-height` set the width/height of the active rectangle, not the chroma subsampling ratio
2. `--format` sets the internal working format, which can not be BYTE. The storage format is encoded in the protocol
3. It is not possible to change the subsampling layout in testapp
4. Is `input_480x272_yuv420p.yuv` 195840 bytes in size?

There are API usage examples in the doc/ directory. Testapp is a test program which uses the internal API

**Comment by suz53** [comment]
Thanks for your reply!

I've tried `api_example_c` using `$ ./api_example_c input_480x272_yuv420p.yuv ./output_1280x720_yuv444p.yuv 480 272 1280 720` and runs successfully. The `input_480x272_yuv420p.yuv` is a yuv video containing 125 frames, thus per-frame size `=24M/125 = 192000bytes`. I was wondering how can I set the pixel_format for input (YUV420P) and output (YUV444P)?

Thanks again!

**Comment by sekrit-twc** [comment]
`api_example_c` is hard-coded for i420. To set other formats, adjust the format descriptor (see: L184).

	/* (2) Fill the format descriptors for the input and output images. */

**Comment by sekrit-twc** [comment]
> CPU-type is set to None by default in this app. Is there a way to utilize SIMD optimizations such as SSE or AVX?

Create a `zimg_graph_builder_params` object and initialize it with `zimg_graph_builder_params_default`. Pass it to `zimg_filter_graph_build` as the third argument.

**Comment by suz53** [comment]
Thanks again!
I've benchmarked the `ZIMG_CPU_NONE` and `ZIMG_CPU_AUTO_64B` and can see around `1.4x` speedup.
Is there a way to find out which optimization (e.g., `X86_SSE` or `X86_AVX`) the runtime has detected?
