### ISSUE TITLE
Multithreading for resize/unresize

### ISSUE THREAD

**Issue by suz53** [sekrit-twc/zimg#149]
I've noticed a `tile_example.cpp` file which utilizes multi-threads.

Is it possible to utilize multi-threads for resampling/scaling, for example, by setting some flags in `api_example_c.c`? 

Thanks!

**Comment by sekrit-twc** [comment]
Multi-threaded processing of a single image is not part of the API. `tile_example` shows how it can be done (for certain operations, under certain conditions). Multi-threaded processing of multiple images (e.g. a video) is as trivial as calling `zimg_filter_graph_process` from multiple threads.

**Comment by suz53** [comment]
Thanks for letting me know.
