### ISSUE TITLE
windows.h not found under llvm-mingw-w64 targeting ARM

### ISSUE THREAD

**Issue by sr55** [sekrit-twc/zimg#151]
Hi,

I'm compiling targeting for ARM64 using a llvm mingw-w64 toolchain.
cpuinfo_arm.cpp is throwing an error that it can't find "Windows.h"

`
rc/zimg/common/arm/cpuinfo_arm.cpp:7:12: fatal error: 'Windows.h' file not found
  #include <Windows.h>
           ^~~~~~~~~~~
`

Changing this to "windows.h" (lowercase) seems to resolve the issue.

Based on https://github.com/sekrit-twc/zimg/pull/42 it looks like such a patch would break other platforms.

I can work around this upstream but wanted to report it if  there are any better suggestions? 

Thanks

**Comment by sekrit-twc** [comment]
This is a bug in MinGW.

**Comment by sr55** [comment]
ok. Thanks
