### ISSUE TITLE
Fixed-point implementation in colorspace using AVX/AVX2

### ISSUE THREAD

**Issue by suz53** [sekrit-twc/zimg#152]
Hi,
I've noticed that the SIMD implementations in colorspace conversion are (mostly) done using floating-point precision, such as `operation_impl_avx.cpp: matrix_filter_line_avx` and `operation_impl_avx2.cpp: to_linear_lut_filter_line`. 

1. Is there a fixed-point implementation already (and I missed)?
2. If not, I would like to implement by myself. After that, is there a "switch" for users to decide to use which version (i.e., floating-point or fixed-point)?

Thanks!

**Comment by sekrit-twc** [comment]
HDR operations can not be done in fixed-point. fixed-point operations are also lossy for BTB/WTW data in various situations.
