### ISSUE TITLE
DepthConvert only converts to floating-point types

### ISSUE THREAD

**Issue by suz53** [sekrit-twc/zimg#153]
I was using `hdr_example` to convert a hdr image to sdr. The first step is `tolinear`.

In order to save memory bandwidth/accesses, rather than `linear_format.pixel_type = ZIMG_PIXEL_FLOAT`, I changed to `linear_format.pixel_type = ZIMG_PIXEL_WORD` or `HALF` to use 16-bit uint16_t type. 
However, the code still goes to `ConvertToFloat()` to convert to 32-bit floating-point before performing colorspace-conversion. I checked the code and found that `DepthConvert only converts to floating point types`; and the `colorspace` operations in X86 only support floating-point implementations. 

Is the `high-precision` the only reason of floating-point-only implementation? If so, is there a way to use `fixed-point` type of implementation in both `DepthConvert` and `Colorspace`?

**Comment by sekrit-twc** [comment]
#152
