### ISSUE TITLE
Possible to post a finished (built and useable) release?

### ISSUE THREAD

**Issue by John-Greg** [sekrit-twc/zimg#163]
Hello.  I wanted to use ZIMG in an AviSynth project.  I came here looking for a finished & ready-to-use release.  When I couldn't t find one, it became a crash course in Git and GitHub and C++ and Cygwin and GNU for more than 2 days--mostly without sleep or food, ha.
---So starting from NO knowledge on the subject (and reluctantly adding 124GB of cygwin files to my computer!), I got all the way up to creating a " cygzimg-2.dll " and bringing it into AviSynth.  However, AviSynth could not load this DLL.  
---I was about to give up when I finally asked the _right_ question on Google: "how to use ZIMG with AviSynth".  And lo and behold, the first hit was <http://avisynth.nl/index.php/Avsresize>.   In other words, exactly what I had been looking for from the beginning.  
---I'm thankful for all the new knowledge & experience I gained in 2 days.   But is there any chance of simply posting this Build download link <https://web.archive.org/web/20211121225346if_/https://files.videohelp.com/u/223002/avsresize_r12.7z> for non-programmers like me, who just want to USE the functions?  Thank you to sekrit-twc and all the other geniuses out there!
(That webpage also, of course, details all the functions in ZIMG, which is helpful for a user.)

**Comment by sekrit-twc** [comment]
z.lib is not an end-user application. It makes no sense to publish releases, as there would be no way to use them. AVSRESIZE is not part of z.lib.

**Comment by John-Greg** [comment]
I see.  Thank you!
