### ISSUE TITLE
Emscripten Web Assembly build fail

### ISSUE THREAD

**Issue by yodofaither** [sekrit-twc/zimg#164]
zimg.cpp:137:5: error: use of undeclared identifier 'ZIMG_CPU_X86_MMX'

**Comment by yodofaither** [comment]
Can I use emcc instead of gcc to compile zimg?

**Comment by sekrit-twc** [comment]
--disable-simd

**Comment by yodofaither** [comment]
> --disable-simd

Many thanks! After add --disable-simd, I was able to build zimg with emcc.If I run`pkg-config --libs zimg`, I get "-L/usr/local/lib -lzimg". However, when I tried to build ffmpeg with `--enable-libzimg` , it failed with "ERROR: zimg >= 2.7.0 not found using pkg-config". I've searched a lot, but nothing really helps. Any help will be a good news, thanks again!
