### ISSUE TITLE
ERROR: zimg >= 2.7.0 not found using pkg-config

### ISSUE THREAD

**Issue by yodofaither** [sekrit-twc/zimg#165]
After add --disable-simd, I was able to build zimg with emcc(Emscripten for Web Assembly).If I run `pkg-config --libs zimg`, I get "-L/usr/local/lib -lzimg". 
However, when I tried to build ffmpeg with --enable-libzimg , it failed with "ERROR: zimg >= 2.7.0 not found using pkg-config". I've searched a lot, but nothing really helps. Any help will be a good news, thanks again!

**Comment by sekrit-twc** [comment]
ffmpeg issue.

**Comment by yodofaither** [comment]
thanks

**Comment by cgeffect** [comment]
how to Solve?

**Comment by lucasmundim** [comment]
@cgeffect adding `--extra-libs="-lm -lstdc++"` to ffmpeg's `./configure` worked for me.
