### ISSUE TITLE
Question: Does Zimg use the GPU at all or possibly could? Especially the FFmpeg zscale filter.

### ISSUE THREAD

**Issue by YousufSSyed** [sekrit-twc/zimg#166]
I'm just wondering if it could or if Zimg runs completely on the CPU.

**Comment by sekrit-twc** [comment]
No GPUs.

**Comment by ValZapod** [comment]
https://github.com/FFmpeg/FFmpeg/search?o=desc&q=cuda_scale&s=committer-date&type=commits

This one is good in ffmpeg, uses CUDA.

**Comment by YousufSSyed** [comment]
I've already seen it a while ago but thanks anyway. I was just wondering if Zimg supports GPUs.
