### ISSUE TITLE
--shared-memory is disallowed by libzimg_internal_la-graphnode.o

### ISSUE THREAD

**Issue by yodofaither** [sekrit-twc/zimg#167]
I had tried to build zimg with multithreads, so I read the `"configure"` file. It said "First of all, check if the user has set any of the `PTHREAD_LIBS`, etcetera environment variables...". So I had set `PTHREAD_CFLAGS` to `"-pthread"` and `PTHREAD_LIBS` to `"lpthread"`, and then built zimg, nothing special happened.

But when built FFmpeg with emcc and set `"-s USE_PTHREADS=1"`, I got "**--shared-memory is disallowed by libzimg_internal_la-graphnode.o**  because it was not compiled with 'atomics' or 'bulk-memory' features“. It seemed like I still had not built zimg with multithread.

So how can I build zimg with multithreads?

**Comment by sekrit-twc** [comment]
Please provide the output of `configure` and any `config.log`. Pthreads are automatically detected by autotools and require no special instructions.

**Comment by yodofaither** [comment]
Thanks for your guidance.Here are my building steps:
1.Configure zimg

**Comment by yodofaither** [comment]
2.Make clean zimg
`emmake make clean` and I got:

> make: make clean
make[1]: Entering directory `/usr/local/zhiying/dependencies/zimg'
test -z "" || rm -f 
test -z "libzimg.la" || rm -f libzimg.la
rm -f ./so_locations
rm -rf .libs _libs
rm -rf doc/example/.libs doc/example/_libs
rm -rf src/testcommon/.libs src/testcommon/_libs
rm -rf src/zimg/api/.libs src/zimg/api/_libs
rm -rf src/zimg/colorspace/.libs src/zimg/colorspace/_libs
rm -rf src/zimg/colorspace/arm/.libs src/zimg/colorspace/arm/_libs
rm -rf src/zimg/colorspace/x86/.libs src/zimg/colorspace/x86/_libs
rm -rf src/zimg/common/.libs src/zimg/common/_libs
rm -rf src/zimg/common/arm/.libs src/zimg/common/arm/_libs
rm -rf src/zimg/common/x86/.libs src/zimg/common/x86/_libs
rm -rf src/zimg/depth/.libs src/zimg/depth/_libs
rm -rf src/zimg/depth/arm/.libs src/zimg/depth/arm/_libs
rm -rf src/zimg/depth/x86/.libs src/zimg/depth/x86/_libs
rm -rf src/zimg/graph/.libs src/zimg/graph/_libs
rm -rf src/zimg/resize/.libs src/zimg/resize/_libs
rm -rf src/zimg/resize/arm/.libs src/zimg/resize/arm/_libs
rm -rf src/zimg/resize/x86/.libs src/zimg/resize/x86/_libs
rm -rf src/zimg/unresize/.libs src/zimg/unresize/_libs
rm -rf src/zimg/unresize/x86/.libs src/zimg/unresize/x86/_libs
rm -rf test/.libs test/_libs
rm -rf test/extra/musl-libm/.libs test/extra/musl-libm/_libs
cd test/extra/googletest/build && make clean
/bin/sh: line 0: cd: test/extra/googletest/build: No such file or directory
make[1]: [clean-local] Error 1 (ignored)
test -z "libzimg_internal.la     " || rm -f libzimg_internal.la     
rm -f ./so_locations
 rm -f
rm -f *.o
rm -f doc/example/*.o
rm -f src/testapp/*.o
rm -f src/testcommon/*.o
rm -f src/testcommon/*.lo
rm -f src/zimg/api/*.o
rm -f src/zimg/api/*.lo
rm -f src/zimg/colorspace/*.o
rm -f src/zimg/colorspace/*.lo
rm -f src/zimg/colorspace/arm/*.o
rm -f src/zimg/colorspace/arm/*.lo
rm -f src/zimg/colorspace/x86/*.o
rm -f src/zimg/colorspace/x86/*.lo
rm -f src/zimg/common/*.o
rm -f src/zimg/common/*.lo
rm -f src/zimg/common/arm/*.o
rm -f src/zimg/common/arm/*.lo
rm -f src/zimg/common/x86/*.o
rm -f src/zimg/common/x86/*.lo
rm -f src/zimg/depth/*.o
rm -f src/zimg/depth/*.lo
rm -f src/zimg/depth/arm/*.o
rm -f src/zimg/depth/arm/*.lo
rm -f src/zimg/depth/x86/*.o
rm -f src/zimg/depth/x86/*.lo
rm -f src/zimg/graph/*.o
rm -f src/zimg/graph/*.lo
rm -f src/zimg/resize/*.o
rm -f src/zimg/resize/*.lo
rm -f src/zimg/resize/arm/*.o
rm -f src/zimg/resize/arm/*.lo
rm -f src/zimg/resize/x86/*.o
rm -f src/zimg/resize/x86/*.lo
rm -f src/zimg/unresize/*.o
rm -f src/zimg/unresize/*.lo
rm -f src/zimg/unresize/x86/*.o
rm -f src/zimg/unresize/x86/*.lo
rm -f test/*.o
rm -f test/api/*.o
rm -f test/colorspace/*.o
rm -f test/colorspace/arm/*.o
rm -f test/colorspace/x86/*.o
rm -f test/depth/*.o
rm -f test/depth/arm/*.o
rm -f test/depth/x86/*.o
rm -f test/extra/musl-libm/*.o
rm -f test/extra/musl-libm/*.lo
rm -f test/extra/sha1/*.o
rm -f test/graph/*.o
rm -f test/resize/*.o
rm -f test/resize/arm/*.o
rm -f test/resize/x86/*.o
test -z "" || rm -f 
test -z "" || rm -f 
test -z "test-suite.log" || rm -f test-suite.log
rm -f *.lo
make[1]: Leaving directory `/usr/local/zhiying/dependencies/zimg'

**Comment by yodofaither** [comment]
3.Make zimg
`emmake make` and I got:

>

**Comment by yodofaither** [comment]
4.Make install zimg
`emmake make install` and I got:

>

**Comment by yodofaither** [comment]
That's all I do with zimg. But when built FFmpeg with emcc and set "-s USE_PTHREADS=1", I still got "**--shared-memory is disallowed by libzimg_internal_la-graphnode.o because it was not compiled with 'atomics' or 'bulk-memory' features“. 
It seemed like I still had not built zimg with multithread**. Please give me a hint of my mistakes.
Thank you very much!

**Comment by yodofaither** [comment]
The problem has been solved and it really works for me. Thank you very much for your help! @sekrit-twc

**Comment by zhaoda** [comment]
Thank you all.
