### ISSUE TITLE
3D LUT color space conversion

### ISSUE THREAD

**Issue by pittalamahesh** [sekrit-twc/zimg#173]
Hi, We are implementing color space conversion(PQ<->HLG) using 3D LUT with tetrahedral interpolation in Zimg. What is the procedure to share patches ? Can we have a conversation about the implementation here ?

**Comment by sekrit-twc** [comment]
This is already covered by timecube.

**Comment by pittalamahesh** [comment]
I couldn't find in zimg repository, can you please locate me ?
Do you have any documentation which you can share it with me ?

**Comment by pittalamahesh** [comment]
got it, it is another repository. Looking into it, thanks

**Comment by pittalamahesh** [comment]
It supports only trilinear interpolation. Does it supports tetrahedral interpolation also ?

I see the CLI format, looks like it takes RGB(xyz) planes. Am I correct ?
test.exe cubefile [x y z] [simd]

**Comment by sekrit-twc** [comment]
Just use trilinear. It's faster. Please feel free to discuss in the appropriate repo.

**Comment by pittalamahesh** [comment]
We have implemented color space conversion(PQ<->HLG) using 3D LUT with tetrahedral interpolation in zimg, is it possible to push patches to the zimg repository ?

**Comment by pittalamahesh** [comment]
Looks like timecube doesn't have integration support with FFmpeg. We are looking for a library which does 3D LUT colorspace conversion and integrates with FFmpeg. Any suggestions ?

**Comment by ValZapod** [comment]
https://github.com/FFmpeg/FFmpeg/commit/716b39674059d5b416faef92afd41654a6d9469b
