### ISSUE TITLE
Crashes due to incorrectly identified avx2 feature

### ISSUE THREAD

**Issue by Zapeth** [sekrit-twc/zimg#176]
When the library code is called, the application (mpv) crashes on my CPU with `SIGILL` in `zimg::depth::left_shift_b2w_avx2`.

https://github.com/sekrit-twc/zimg/pull/174 would fix this, but it was closed without comment.

**Comment by sekrit-twc** [comment]
Where is this CPU.

**Comment by Zapeth** [comment]
I don't see how this is relevant to the issue, as quoted in the linked discussion, the Intel instruction manual clearly says
> If a value entered for CPUID.EAX is higher than the maximum input value for basic or extended function for that processor then the data for the highest basic information leaf is returned.

This is not done in your code, meaning any CPU that doesn't support a higher feature level than requested (eax=7 in this case) returns data that might lead to an incorrectly identified feature set.

If you don't want to implement a trivial fix, then feel free to close this issue. I already spent a disproportional amount of time on this, so I'm not going to bother with more interactions here.

**Comment by sekrit-twc** [comment]
If you don't want to contribute, that is on you, not me.
