### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by nobodyatandnothing** [sekrit-twc/zimg#181]
```
> git clone https://github.com/sekrit-twc/zimg
> cd zimg
> ./autogen.sh
> ./configure --disable-static
> make
make[1]: Entering directory '/home/g/git-pkges/media/zimg'
  CXX      dummy.lo
make[1]: *** No rule to make target 'graphengine/graphengine/cpuinfo.cpp', needed by 'graphengine/graphengine/libzimg_internal_la-cpuinfo.lo'.  Stop.
make[1]: Leaving directory '/home/g/git-pkges/media/zimg'
make: *** [Makefile:4172: all-recursive] Error 1
```

**Comment by james28909** [comment]
i get same error, commented out all lines with zimg and also removed zimg from ffmpeg build options. now it is still building, just without zimg support lol

**Comment by james28909** [comment]
EDIT: actually i just changed to the v3.0 branch and it seems to get past this error. we will see if the build completes though lol

**Comment by mrkapqa** [comment]
same here, 
git clone - build fails, downloading manually version 3.0.x and building that one succeeds.

**Comment by Nomis101** [comment]
This is due to the two issues mentioned in this commit.
https://github.com/sekrit-twc/zimg/commit/e4acb3a29d7c45faca902b490a1585fe48063970

**Comment by styler00dollar** [comment]
Can confirm, current git master is broken, v3.0.4 release works.

**Comment by james28909** [comment]
libbluray is having issues as well, atleast for me it is. i had to clone it manually into the correct folder, then edit the scripts lines for git checkout, and then it built great. this helper script can actually help cross compile a plethora of stuff. i been compiling for 2 days straight and aint but about half way through lol

**Comment by mrkapqa** [comment]
don't know about this "zimg" , but with the "3.0.4" release instead of the git-clone , which at the moment fails with the above
`make[1]: *** No rule to make target 'graphengine/graphengine/cpuinfo.cpp', needed by 'graphengine/graphengine/libzimg_internal_la-cpuinfo.lo'.  Stop.
make[1]: Leaving directory '/home/g/git-pkges/media/zimg'
make: *** [Makefile:4172: all-recursive] Error 1`

the mpv-build completes, but results in error with amdgpu graphics when playing back video files

`Error opening/initializing the selected video_out (--vo) device.
`

don't know if zimg and mpv-build are affiliated in any way, so please forgive if am posted this here and was not supposed to be.

**Comment by mrkapqa** [comment]
`'/home/rich/Programs/zimg'
make[1]: *** No rule to make target 'graphengine/graphengine/cpuinfo.cpp', needed by 'graphengine/graphengine/libzimg_internal_la-cpuinfo.lo'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CXX      dummy.lo
make[1]: Leaving directory '/home/rich/Programs/zimg'
`

**Comment by james28909** [comment]
> don't know about this "zimg" , but with the "3.0.4" release instead of the git-clone , which at the moment fails with the above `make[1]: *** No rule to make target 'graphengine/graphengine/cpuinfo.cpp', needed by 'graphengine/graphengine/libzimg_internal_la-cpuinfo.lo'. Stop. make[1]: Leaving directory '/home/g/git-pkges/media/zimg' make: *** [Makefile:4172: all-recursive] Error 1`
> 
> the mpv-build completes, but results in error with amdgpu graphics when playing back video files
> 
> `Error opening/initializing the selected video_out (--vo) device. `
> 
> don't know if zimg and mpv-build are affiliated in any way, so please forgive if am posted this here and was not supposed to be.

Are you trying to build with the [ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers) script? if so, i was just looking through the `cross_compile_ffmpeg.sh` script, and i seen something that might benefit you somehow? not sure though. but ctrl+f this (if youre using the helper script mentioned above in this comment):
```
if [[ $build_amd_amf = y ]]; then
    build_amd_amf_headers
```
maybe somehow you built with the wrong option/flag somehow? maybe when you run the `cross_compile_ffmpeg.sh` script, you need to specify `--build_amd_amf=y` option. Hopefully this helps you somehow. 

Good luck though!

**Comment by mrkapqa** [comment]
@james28909 thank you, but i am still using Linux, don§t know if those apply.

Tried today again, on a differnt computer, same result: 

1. zimg via `git clone https://github.com/sekrit-twc/zimg.git` fails to build with `  CXX      dummy.lo
make[1]: *** No rule to make target 'graphengine/graphengine/cpuinfo.cpp', needed by 'graphengine/graphengine/libzimg_internal_la-cpuinfo.lo'.  Stop.
make[1]: Leaving directory '/home/rich/Downloads/zimg'
Makefile:4028: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`
2. building zimg via 3.0.4.zip succeeds
3. however, resulting mpv with vapoursynth would no longer play?   `Error opening/initializing the selected video_out (--vo) device.
Video: no video`

i am using AMD graphics driver on Ubuntu 18.04 Bionic this time.

**Comment by Nomis101** [comment]
@[mrkapqa](https://github.com/mrkapqa) You need to init the new submodule.
```
git clone https://github.com/sekrit-twc/zimg.git
cd zimg
git submodule update --init --recursive
```

Then autogen and build it like before.

**Comment by mrkapqa** [comment]
@Nomis101, thanks, it would build with these instructions, but resulting mpv player still shows
`Error opening/initializing the selected video_out (--vo) device.
`
i tried now with both Nvidia and AMD Graphics card, so i am at odds, it seems no graphics cards driver issue.
