### ISSUE TITLE
graphengine submodule bug

### ISSUE THREAD

**Issue by adrian-sal-kennedy** [sekrit-twc/zimg#185]
As of a while now, trying to build (I've only tried ubuntu 22.10 but that's probably not relevant) from a fresh clone will fail.

I managed to get it to work thus:
- clone
- git submodule init
- rm -rf ./graphengine/*
- git submodule update

It seems there are files inside that folder coming through on cloning zimg, and that's preventing git from cloning the submodule, causing the whole thing to fail to build.

**Comment by sekrit-twc** [comment]
Works for me on Ubuntu 22.04:

````
$ git clone https://github.com/sekrit-twc/zimg.git
$ cd zimg
$ git submodule update --init --recursive
$ ./autogen.sh
$ ./configure
$ make
````
