### ISSUE TITLE
Error when using libzimg in stataic build: multiple definition of `powf'

### ISSUE THREAD

**Issue by CharlesMengCA** [sekrit-twc/zimg#188]
Hi, 

Sorry for bothering you here:

When I tried to build mpv for windows with some customized configuration, I got following error. It might be related to libm_wrapper.

The build environment is crossing compile on Arch Linux for Windows

Could you check if you can fix this?

\~/mpv-winbuild-cmake/build64/install/lib/gcc/x86_64-w64-mingw32/12.2.1/../../../../x86_64-w64-mingw32/bin/ld: \~/mpv-winbuild-cmake/build64/install/mingw/lib/libzimg.a(libzimg_internal_la-libm_wrapper.o):libm_wrapper.c:(.text$powf[powf]+0x0): multiple definition of `powf';  \~/mpv-winbuild-cmake/build64/install/mingw/lib/libmingwex.a(lib64_libmingwex_a-powf.o):~/mpv-winbuild-cmake/build64/toolchain/mingw-w64-prefix/src/mingw-w64/mingw-w64-crt/math/powf.c:8: first defined here

**Comment by CharlesMengCA** [comment]
Could be related to? 

libm_wrapper.cpp

`float (*zimg_x_powf)(float, float) = powf;`

**Comment by sekrit-twc** [comment]
No.
