### ISSUE TITLE
Crash in ordered_dither_w2b_neon

### ISSUE THREAD

**Issue by chainikdn** [sekrit-twc/zimg#189]
So, there's an Android video player using mpv + Vapoursynth + zimg.
I built native libs more than a year ago - mpv 0.34, Vapoursynth R52, zimg 3.0.1, since then they were not changed at all.

Back in November Google said I must update target API level to 31 for the Google Play release, so I did. And just after that the whole new crash appeared in the Play console. With the very same native libs as before, exactly _nothing_ changed there.

Since all the libs were stripped there were no details except the crash occurs somewhere in zimg.
So I made a new release with updated and not stripped libs: mpv 0.35, Vapoursynth R57, zimg latest git.
Now the stack looks like this:
```
  #00  pc 0x0000000000033f3c  /lib/arm64/libzimg.so (zimg::depth::ordered_dither_w2b_neon(float const*, unsigned int, unsigned int, void const*, void*, float, float, unsigned int, unsigned int, unsigned int))
  #01  pc 0x0000000000028ba8  /lib/arm64/libzimg.so (zimg::depth::(anonymous namespace)::OrderedDither::process(graphengine::BufferDescriptor const*, graphengine::BufferDescriptor const*, unsigned int, unsigned int, unsigned int, void*, void*) const)
  #02  pc 0x000000000001ae7c  /lib/arm64/libzimg.so (graphengine::zimg::(anonymous namespace)::TransformNodeSimple::process(graphengine::zimg::FrameState*, unsigned int, unsigned int) const)
  #03  pc 0x0000000000018fe0  /lib/arm64/libzimg.so (graphengine::zimg::GraphImpl::impl::run_node(graphengine::zimg::Node*, graphengine::zimg::GraphImpl::impl::SimulationResult const&, graphengine::Graph::Endpoint const*, unsigned int, void*) const)
  #04  pc 0x0000000000016ef8  /lib/arm64/libzimg.so (graphengine::zimg::GraphImpl::impl::run(graphengine::Graph::Endpoint const*, void*) const)
  #05  pc 0x0000000000015254  /lib/arm64/libzimg.so (graphengine::zimg::GraphImpl::run(graphengine::Graph::Endpoint const*, void*) const)
  #06  pc 0x00000000000293bc  /lib/arm64/libzimg.so (zimg::graph::FilterGraph::process(std::__ndk1::array<graphengine::BufferDescriptor, 4ul> const&, std::__ndk1::array<graphengine::BufferDescriptor, 4ul> const&, void*, int (*)(void*, unsigned int, unsigned int, unsigned int), void*, int (*)(void*, unsigned int, unsigned int, unsigned int), void*) const)
  #07  pc 0x000000000001be80  /lib/arm64/libzimg.so (zimg_filter_graph_process+376)
  #08  pc 0x0000000000099b04  /lib/arm64/libvapoursynth.so ((anonymous namespace)::vszimg_get_frame(int, int, void*, void**, VSFrameContext*, VSCore*, VSAPI const*))
  #09  pc 0x000000000008d8a4  /lib/arm64/libvapoursynth.so (VSNode::getFrameInternal(int, int, VSFrameContext*))
```
This doesn't happens all the time, I can't reproduce this on any of my devices. It's like 1% crash rate.
I have neither the exact Vapoursynth script nor the video file's details playing at the time of crash.
The script is not constant, it's generated on-the-fly, but there're only a few simple transformations inside, like
```
input_um = clip.resize.Point(format=vs.YUV420P8,dither_type="random")
input_m = input_m.std.CropRel(314,314,140,140)
input_m = input_m.resize.Bicubic(1280,688,filter_param_a=0,filter_param_b=0.75)
```

Any ideas?

**Comment by chainikdn** [comment]
Updated script, removed "dither_type="random" completely, now all resizes are made with default dither_type which is "none".
And it still crashes there. How is it possible?

**Comment by sekrit-twc** [comment]
Need core dump or repro to debug.

**Comment by chainikdn** [comment]
I wish I have it...
I wonder is it normal that the code path reaches OrderedDither w/o any dithering specified in the script?

**Comment by sekrit-twc** [comment]
Yes, all inexact bitdepth conversions go through the dither kernel. The "none" dither pattern is implemented as an all-zeros pattern.

**Comment by chainikdn** [comment]
I believe this may happen if we're converting a 10-bit video with **width isn't divisible by 8** to 8-bit depth.

**Comment by sekrit-twc** [comment]
Thanks. Can you run some of these scenarios through Valgrind or ASan? Create a blank clip script with those resolutions and run the frames through vspipe.

**Comment by chainikdn** [comment]
vspipe crashes on this:
```
import vapoursynth as vs
clip = vs.core.std.BlankClip(format=vs.YUV420P10, width=380, height=720)
out = clip.resize.Point(format=vs.YUV420P8)
out.set_output()
```

**Comment by chainikdn** [comment]
ok, it crashes on the last 4 bytes of the last line, here: https://github.com/sekrit-twc/zimg/blob/90bf82c7202fa5fd37775db3c98799be899231f6/src/zimg/depth/arm/dither_neon.cpp#L160
where line is 719, left=0, right=380
looks like StoreU8::store8_idxlo actually writes 8 bytes instead of 4

**Comment by sekrit-twc** [comment]
Can you print the buffer stride? z.lib assumes it is always ok to write up to 16 bytes to an aligned address, so store8 does a read-modify-write. Back up the call stack to `OrderedDither::process` and print the contents of the second arguments: `Ordered Dither::process(graphengine::BufferDescriptor const* in, graphengine::BufferDescriptor const* out, ...)`, i.e. *out in the debugger or printf.

**Comment by chainikdn** [comment]
stride is ok, 384

**Comment by chainikdn** [comment]
It's interesting that the following script crashes at exactly same point for the same reason, despite there's no 10->8 conversion at all and absolutely no need (?) for any dithering:
```
clip = vs.core.std.BlankClip(format=vs.YUV420P8, width=1920, height=1080, length=1)
out = clip.resize.Point(956,720)
```

**Comment by sekrit-twc** [comment]
> but vst1q_u8 stores 16 bytes, not 8, doesn't it? :/
Yes, I think this must be the issue. The end of row logic needs a fix, because it's storing 16 bytes, starting from j=376, which writes past the aligned end of buffer at j=384. Thanks for helping debug.

>despite there's no 10->8 conversion at all and absolutely no need (?) for any dithering
Resizing always expands to 16-bit, which is why dithering is invoked.

**Comment by sekrit-twc** [comment]
Can you confirm if 3fe44e2 fixes the issue?

**Comment by chainikdn** [comment]
yep, thanks
