### ISSUE TITLE
Feature request: ST 428-1 transfer function (gamma 2.6) support

### ISSUE THREAD

**Issue by kasper93** [sekrit-twc/zimg#192]
Hi,

I cannot wrap my head around how to use zimg to specify X'Y'Z' DCI-P3 input. 

Ideally I would like to do:
```
src.color_family = ZIMG_COLOR_RGB; // XYZ
src.matrix_coefficients = ZIMG_MATRIX_RGB; // XYZ
src.transfer_characteristics = ZIMG_TRANSFER_ST428; // XYZ Gamma 2.6
src.color_primaries = ZIMG_PRIMARIES_ST431_2; // DCI-P3
```

Since `ZIMG_TRANSFER_ST428` doesn't exists I tried with different values there, but it resulted with overly green image. Conversion works if I set `src.color_primaries = ZIMG_PRIMARIES_ST428`, but then I have wrong white point, because I suppose to use DCI-P3. 

What's the proper way to handle this case?

-Kacper

**Comment by sekrit-twc** [comment]
>X'Y'Z' DCI-P3 input.

XYZ and P3 are mutually exclusive. From the rest of your question, I assume you are talking about P3 RGB

- ST.428: [XYZ](https://en.wikipedia.org/wiki/File:CIE1931xy_blank.svg), R=X, G=Y, B=Z
- ST.431-2: DCI-P3 (Cinema) with white point (0.314, 0.351)
- ST.432-1: Apple P3 (Display) with white point D65

**Comment by kasper93** [comment]
Ok, in fact I read some more after creating issue and indeed only thing that is missing is the st428 transfer function. I though XYZ input has different white point, but it has `[1/3, 1/3]` as expected. Thanks  for explanation, I mixed few things up.

I guess I will rename it to future request for st428 transfer function.

**Comment by sekrit-twc** [comment]
I added experimental support for gamma 2.6 in ad449e6. Can you test if it works as expected?

**Comment by kasper93** [comment]
There is break missing in switch. Works ok after fixing this. Also would be nice to bump api version to know if `ZIMG_TRANSFER_ST428` is available.
```
diff --git a/src/zimg/api/zimg.h b/src/zimg/api/zimg.h
index 1a4fb14..9e7ba48 100644
--- a/src/zimg/api/zimg.h
+++ b/src/zimg/api/zimg.h
@@ -29,7 +29,7 @@ extern "C" {
  */
 #define ZIMG_MAKE_API_VERSION(x, y) (((x) << 8) | (y))
 #define ZIMG_API_VERSION_MAJOR 2
-#define ZIMG_API_VERSION_MINOR 4
+#define ZIMG_API_VERSION_MINOR 5
 #define ZIMG_API_VERSION ZIMG_MAKE_API_VERSION(ZIMG_API_VERSION_MAJOR, ZIMG_API_VERSION_MINOR)

 /**
diff --git a/src/zimg/colorspace/gamma.cpp b/src/zimg/colorspace/gamma.cpp
index 3fa1398..c7e6781 100644
--- a/src/zimg/colorspace/gamma.cpp
+++ b/src/zimg/colorspace/gamma.cpp
@@ -358,6 +358,7 @@ TransferFunction select_transfer_function(TransferCharacteristics transfer, doub
        case TransferCharacteristics::ST_428:
                func.to_linear = st_428_eotf;
                func.to_gamma = st_428_inverse_eotf;
+               break;
        case TransferCharacteristics::ARIB_B67:
                func.to_linear = scene_referred ? arib_b67_inverse_oetf : arib_b67_eotf;
                func.to_gamma = scene_referred ? arib_b67_oetf : arib_b67_inverse_eotf;
```

**Comment by sekrit-twc** [comment]
Thanks for testing. The API version doesn't get bumped when colorspaces are added. However, the library version will get bumped in the next release, either 3.0.5 or 3.1, and you can check against that.

**Comment by kasper93** [comment]
> The API version doesn't get bumped when colorspaces are added.

library version is not defined in header, so hard to check if `ZIMG_TRANSFER_ST2084` is available at compile time.

I'm writing, because they define this normalization factor `48/52.37`, so to be fully inline with spec, we could do, whatever small difference does it make.

```
return x < 0.0f ? 0.0f : (52.37f / 48.0f) * zimg_x_powf(x, 2.6f);
```
```
return x < 0.0f ? 0.0f : zimg_x_powf(x * (48.0f / 52.37f), 1.0f / 2.6f);
```

**Comment by sekrit-twc** [comment]
>library version is not defined in header, so hard to check if ZIMG_TRANSFER_ST2084 is available at compile time.

This is true, but it was also the case in the past. You still need to check the library version at runtime or else you will receive an error.

>I'm writing, because they define this normalization factor 48/52.37, so to be fully inline with spec, we could do, whatever small difference does it make.

This needs some verification from actual content. If we applied this factor, it would essentially result in gamma value 1.0 (or the max allowed int value) producing a WTW value in linear light. Does the transform without the scaling factor cause the full range of the linear light (0-1) not to be used?

With scaling: Gamma 1.0 = Linear 1.25. Linear 1.0 = Gamma 0.967

Without scaling Gamma 1.0 = Linear 1.0

Since you have access to the DCI content, could you check which interpretation is correct? If it is the former, you should expect the code value of 1.0 to be rarely present in the content, perhaps only on specular highlights. Likewise, any fades to white should be at a sub-1.0 code value.

**Comment by kasper93** [comment]
> This is true, but it was also the case in the past. You still need to check the library version at runtime or else you will receive an error.

The point is that to use it I need to redefine `ZIMG_TRANSFER_ST428` value and check during runtime if can be used, which is weird thing to do instead of just `#if VER > X` guard all usages of it. 

> This needs some verification from actual content. If we applied this factor, it would essentially result in gamma value 1.0 (or the max allowed int value) producing a WTW value in linear light. Does the transform without the scaling factor cause the full range of the linear light (0-1) not to be used?

Yes, I can't tell for all the content, but this is pretty clear after reading ST 428-1 and EG 432-1 which explains in more detail why normalization exists.

You can see this example https://0x0.st/ohOe.jp2 
Values are in ranges
```
X: [0 , 3888]
Y: [0 , 3961]
Z: [0 , 4095]
```
and after processing it as described in ST 428-1, `img = pow(img / 4095.0, 2.6) * (52.37 / 48)`
we get 
```
X: [ 0.0 , 0.953387485522 ]
Y: [ 0.0 , 1.00063057959 ]
Z: [ 0.0 , 1.09104166667 ]
```

3960 as defined corresponds to 48.0 nits of reference project. And indeed this doesn't exceeds this value in file, in the above example it is 1 above, but well it is within range...

I can provide short sample if you want to analyze this by yourself.

**Comment by sekrit-twc** [comment]
Thanks. I added the normalization factor.
