### ISSUE TITLE
srgb and linear trc inconsistent with ffmpeg/colorspace

### ISSUE THREAD

**Issue by gsimko** [sekrit-twc/zimg#193]
I tried running two transfer function conversions, once converting a bt709 video using ffmpeg/zimg and once with ffmpeg/colorspace. The results look significantly different, the zimg one being a lot darker - both when converting to trc=srgb and to trc=linear. What could cause such a discrepancy?

The commands I use:
ffmpeg -y -i input.mp4 -vf "colorspace=primaries=bt709:trc=linear:space=bt709,format=pix_fmts=yuvj420p" output.mp4
ffmpeg -y -i input.mp4 -vf "zscale=p=709:t=linear:m=709,format=pix_fmts=yuvj420p" output.mp4

I'm not sure which library is right as quicktime shows both significantly differently than the source material.
For sanity checking I also tried converting to bt2020 and smpte170m and those look as expected: no change compared to input.

**Comment by sekrit-twc** [comment]
It appears the difference is that z.lib conforms to the ITU-R BT.1886 standard for interpreting BT.709, whereas FFmpeg does not.
