### ISSUE TITLE
AVX assembly bug in Spline64 resize (C++, AVX2, AVX512 unaffected)

### ISSUE THREAD

**Issue by FranceBB** [sekrit-twc/zimg#209]
As per the discussion on Doom9 (international encoding forum) https://forum.doom9.org/showthread.php?t=173986&page=18 there's a bug in the resample_filter_uv when the kernel selected is "Spline64" and the assembly code used is the AVX one (i.e cpu_type="avx") that causes a row of pixels at the bottom of the picture to be without chroma (i.e completely grey, luma only).

This can be reproduced with the following script:

```
source=ColorBars(500, 960, pixel_type="YV16").Crop(0, 0, -0, -940)

z_ConvertFormat(source, pixel_type="YUV444P16", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx")
z_ConvertFormat(pixel_type="YUV420P10", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx")
avx=last

z_ConvertFormat(source, pixel_type="YUV444P16", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx2")
z_ConvertFormat(pixel_type="YUV420P10", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx2")
avx2=last

StackHorizontal(avx, avx2)
```

Here you can see how the output produced by the AVX assembly code (left) has the issue, while the one produced by AVX2 (right) doesn't:

![image](https://github.com/user-attachments/assets/b1db7722-628d-494f-91b5-0e4df5fb15bc)

I also tried all the other assemblies and luckily enough the issue is present only in the AVX code path.
This is the full test with plain C++, AVX, AVX2, AVX512:

```
source=ColorBars(500, 960, pixel_type="YV16").Crop(0, 0, -0, -940)

z_ConvertFormat(source, pixel_type="YUV444P16", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="none")
z_ConvertFormat(pixel_type="YUV420P10", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="none")
Subtitle("C++")
cpp=last

z_ConvertFormat(source, pixel_type="YUV444P16", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx")
z_ConvertFormat(pixel_type="YUV420P10", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx")
Subtitle("AVX")
avx=last


z_ConvertFormat(source, pixel_type="YUV444P16", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx2")
z_ConvertFormat(pixel_type="YUV420P10", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx2")
Subtitle("AVX2")
avx2=last

z_ConvertFormat(source, pixel_type="YUV444P16", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx512f")
z_ConvertFormat(pixel_type="YUV420P10", resample_filter_uv="Spline64", dither_type="error_diffusion", cpu_type="avx512f")
Subtitle("AVX512")
avx512=last

StackVertical(cpp, avx, avx2, avx512)
```

![image](https://github.com/user-attachments/assets/65ea748b-306c-4cd4-b4dc-49eaadaf45f2)

**Comment by sekrit-twc** [comment]
Should be fixed

**Comment by FranceBB** [comment]
Wow, that was fast! Thank you for that. :D
Yes, I can confirm that the problem has been solved. :) 

![image](https://github.com/user-attachments/assets/4c12e729-0245-4b1f-9302-6564a1573382)

Debug build:
[avsresize.zip](https://github.com/user-attachments/files/17523207/avsresize.zip)
