### ISSUE TITLE
approximate_gamma issue on Linux with AMD 7900X CPU

### ISSUE THREAD

**Issue by this-username-is-already-taken** [sekrit-twc/zimg#211]
I don't know what the exact cause is, but there's an issue when converting RGB to YUV for a color conversion and approximate_gamma=true.
I'm experiencing the problem running VapourSynth on MX Linux (AMD 7900X CPU), or with AVSResize running in Wine, but not when running the Windows version of either program on Windows 11 in VirtualBox. I initially mentioned the problem at doom9 and nobody running Windows in the doom9 thread could duplicate it.

```
clipA = \
BlankClip(color=color_red)\
.ConvertToYUV420(matrix="rec2020")\
.Spline36Resize(240,240)\
.ConvertBits(16)

clipB = clipA\
.HistoTop().Subtitle("BlankClip")

clipC = clipA\
.z_ConvertFormat(colorspace_op="2020:2020:2020:limited=>rgb:linear:xyz:full", pixel_type="RGBP16")\
.z_ConvertFormat(colorspace_op="rgb:linear:xyz:full=>709:709:709:limited", pixel_type="YUV420P16")\
.HistoTop().Subtitle("ag true")

clipD= clipA\
.z_ConvertFormat(colorspace_op="2020:2020:2020:limited=>rgb:linear:xyz:full", pixel_type="RGBP16", approximate_gamma=false)\
.z_ConvertFormat(colorspace_op="rgb:linear:xyz:full=>709:709:709:limited", pixel_type="YUV420P16", approximate_gamma=false)\
.HistoTop().Subtitle("ag false")

clipE= clipA\
.z_ConvertFormat(colorspace_op="2020:2020:2020:limited=>rgb:linear:xyz:full", pixel_type="RGBP16", approximate_gamma=false)\
.z_ConvertFormat(colorspace_op="rgb:linear:xyz:full=>709:709:709:limited", pixel_type="YUV420P16", cpu_type="avx512f")\
.HistoTop().Subtitle("ag true     cpu_type avx512f")

StackHorizontal(clipB, clipC, clipD, clipE)
```

![picA](https://github.com/user-attachments/assets/159d615e-f32b-4bf0-b10c-a5b80d8ba1c0)

There's also something odd happening when limiting the CPU instructions for Avisynth itself (running in Wine) that wasn't effecting anyone at doom9 running Windows. I haven't investigated whether it's possible to limit the CPU the same way in VapourSynth so I don't know if it's a zimg issue as such. It might be some sort of Wine anomaly.

The same script as above, only with SetMaxCPU("ssse3") added to the beginning.

![picB](https://github.com/user-attachments/assets/9449fdbc-caf4-4e47-bf4e-f7e99334eed4)

Cheers!

**Comment by FranceBB** [comment]
Doom9 reference: https://forum.doom9.org/showthread.php?t=173986&page=19

**Comment by sekrit-twc** [comment]
The first issue with the darkening is fixed. The other issue with the green image is not reproduced.

**Comment by this-username-is-already-taken** [comment]
It's probably the same issue, but I have a question anyway....
I realized after reporting the bug that the same thing was happening without the need to convert to/from RGB.

```
z_ConvertFormat(colorspace_op="2020:2020:2020:limited=>709:709:709:limited", pixel_type="YUV420P16")
```
My question though is....
It seems to be traditional for color conversions to be done by converting to RGB first then back to YUV, but while I was experimenting, at least with single colors, there appeared to be no difference between a direct conversion and converting to RGB first, so I was wondering if it's necessary for zimg. The only exception to that rule I've found so far is when the color being converted is red. I've only played around with conversions from rec.2020 to rec.709 at the moment.

Thanks!

```
clip = BlankClip(color=color_purple).ConvertToYUV420(matrix="rec2020").Spline36Resize(240,240).ConvertBits(16)
clipB = clip\
.z_ConvertFormat(colorspace_op="2020:2020:2020:limited=>rgb:linear:xyz:full", pixel_type="RGBP16", approximate_gamma=false)\
.z_ConvertFormat(colorspace_op="rgb:linear:xyz:full=>709:709:709:limited", pixel_type="YUV420P16", approximate_gamma=false)
clipC = clip\
.z_ConvertFormat(colorspace_op="2020:2020:2020:limited=>709:709:709:limited", pixel_type="YUV420P16", approximate_gamma=false)
Compare(clipB, clipC)
```
![picC](https://github.com/user-attachments/assets/c73ec736-2d68-4034-b041-02eae5a3d564)

![picD](https://github.com/user-attachments/assets/4dd80c51-75f6-46b1-9622-ac935796ee1e)

**Comment by sekrit-twc** [comment]
z.lib will automatically convert YUV to RGB when performing a colorspace conversion. Creating an intermediate RGB clip may affect the result if the input has out-of-range colors and the intermediate format is integer, as this will cause clipping.

**Comment by this-username-is-already-taken** [comment]
Thanks for the info.
