### ISSUE TITLE
Developer inquiry thread

### ISSUE THREAD

**Issue by sekrit-twc** [sekrit-twc/zimg#26]
For questions.

**Comment by dubhater** [comment]
I have a question. Why doesn't your cat appear next to every commit?

**Comment by sekrit-twc** [comment]
Sadly, Cathub attaches cat pictures to commits by email. Only the sekrit-twc.noreply.github.com address from the internal editor triggers cat-ness.

**Comment by richardpl** [comment]
Is api in zimg3.h header gonna be removed or just header renames and numbers removed?
I like api in zimg3.h

I cant compile zimg on x64 with clang 3.7 on ubuntu 14.04 it complains about missing half float instruction or something.

**Comment by sekrit-twc** [comment]
zimg3.h will be renamed to zimg.h in the release version of 2.0. "zimg2" prefixed functions may be renamed to "zimg", depending on whether not or API v1 compatibility is retained. If you are having intrinsics-problems, please configure without "enable-x86simd" which is not currently implemented.

As an aside, Clang is not a regularly tested target, and I believe its intrinsics implementation is non-conforming. GNU C is the officially supported compiler for POSIX platforms.

**Comment by richardpl** [comment]
Which gcc version?

**Comment by sekrit-twc** [comment]
Travis-CI regularly tests against GCC 5. To my knowledge, GCC 4.8 and 4.9 also work.

**Comment by sekrit-twc** [comment]
I learned about this cool Web 2.0 thing:

https://gitter.im/sekrit-twc/zimg
