### ISSUE TITLE
Unable to build under clang

### ISSUE THREAD

**Issue by invisiblearts** [sekrit-twc/zimg#34]
Clang is far more strict with the standard of C++, and thus do not support some GNU/MSVC extensions.
One error it gives is about thread_local (not supported under libc++).
The other I'm not very sure about, just giving the raw text.
```
./src/zimg/graph/image_buffer.h:135:13: error: use 'template' keyword to treat
      'static_buffer_cast' as a dependent template name
        return buf.static_buffer_cast<U>();
                   ^
                   template
```

**Comment by invisiblearts** [comment]
And I would appreciate it very much if it could be fixed, or at least workarounds at the cost of performance, as VapourSynth-Editor relies on zimg, and the Qt Framework is extremely difficult to compile with gcc on OS X.

**Comment by dubhater** [comment]
As far as I can tell, vsedit still uses its own internal copy of zimg (pretty old by now), so you don't need to compile zimg yourself separately.

**Comment by invisiblearts** [comment]
Well, the current copy of zimg in vsedit has the same issue, and therefore I think requesting changes here is more reasonable.

**Comment by sekrit-twc** [comment]
`thread_local` is not an extension. It is a fundamental part of ISO C++. I have fixed the issue with the missing `template` qualifier though.

**Comment by invisiblearts** [comment]
Okay, it seems that all is Apple's fault. The open-source version of clang should work fine. Thanks anyway.

**Comment by sekrit-twc** [comment]
FWIW, `-Dthread_local=__thread` might work on CLANG. No warranty provided though.
