### ISSUE TITLE
GCC 6 build issue

### ISSUE THREAD

**Issue by alucryd** [sekrit-twc/zimg#48]
Hi,

I'm hitting an error trying to build v2.1 with GCC 6.1.1 on Arch Linux, could you please have a look at it? Here's the build log: https://paste.xinu.at/pN6Lo/

Thx in advance.

**Comment by sekrit-twc** [comment]
Can you try with "./configure CXXFLAGS='-std=c++1z'"? Google says that GCC 6 dropped support for hexfloats.

**Comment by alucryd** [comment]
Works like a charm, thx :)
