### ISSUE TITLE
was 2.1 retagged?

### ISSUE THREAD

**Issue by ilovezfs** [sekrit-twc/zimg#49]
We're seeing a checksum mismatch on the 2.1 release for Homebrew. Was the tag deleted and re-created?

**Comment by ilovezfs** [comment]
RE:
https://github.com/Homebrew/homebrew-core/pull/1359
https://github.com/Homebrew/brew/issues/397

**Comment by sekrit-twc** [comment]
If it were, it wasn't recently.

**Comment by ilovezfs** [comment]
Thanks for clarifying! In the future, if you re-tag, making it like "2.1.1" helps to soothe our paranoia :)

Also, you may want to start gpg signing your tags, for which GitHub recently added some pretty nice support: https://github.com/blog/2144-gpg-signature-verification
