### ISSUE TITLE
Interlaced clip problem

### ISSUE THREAD

**Issue by HolyWu** [sekrit-twc/zimg#51]
```python
import vapoursynth as vs
core = vs.get_core()

clip = core.std.BlankClip(format=vs.YUV420P8)
clip = core.std.SetFrameProp(clip, prop="_FieldBased", intval=2)
clip = core.resize.Point(clip, height=clip.height + 8, src_height=clip.height + 8)

clip.set_output()
```

I get an error message of `Resize error 3076: image shift or subwindow too great`. The error disappears if `_FieldBased` is set to 0.

**Comment by sekrit-twc** [comment]
This is a VS bug. I guess it passes src_width/src_height as the frame size instead of the field size.
