### ISSUE TITLE
question regarding sRGB white point luminance and black level scaling

### ISSUE THREAD

**Issue by dzung-hoang** [sekrit-twc/zimg#66]
I am reviewing https://www.w3.org/Graphics/Color/srgb and found the following information.

1. Reference display white point luminance: 80 cd/m<sup>2</sup>.
I believe your code normalizes linear RGB value of 1 to represent 100 cd/m<sup>2</sup>. Should a correction factor be applied for sRGB since it's reference display white point is 80 cd/m<sup>2</sup>?

2. There is also mention of "black normalized values" being computed for ICC v4.
Is this being handled with the range (full vs. limited) option?

**Comment by sekrit-twc** [comment]
1. The nominal white point is only used when converting to an absolute luminance scale (ST.2084). I do not see why sRGB (i.e. computer) images should be handled differently from BT.709 (i.e. television) images. Moreover, I believe sRGB only describes the reference viewing condition. No actual sRGB display runs at 80 cd/m^2, which is usually not even physically possible.

2. Full/limited range is only about quantization. It is not considered by the colorspace module, which works only on real numbers. I am not familiar with ICC, but in color management, there is the notion of black point compensation when adapting images for real displays (to avoid black crush, etc.). z.lib does not consider this. It is related to tone mapping.

**Comment by dzung-hoang** [comment]
The use cases I'm considering include overlaying video and graphics from difference sources. In these use cases, making sure the difference sources have the same luminance scale is very important. I don't believe that peak_luminance parameter is supported for sRGB, so adding that support would help.

Matching reference white and black points would also apply to my use cases.

**Comment by sekrit-twc** [comment]
For relative transfer functions, there is no specific correction needed to change the brightness level, so e.g. a sRGB graphic can be embedded on a BT.709 image simply by adjusting the nonlinearity (i.e. BT.709 = pow(pow(sRGB, 2.2), 1 / 2.4). Black point compensation is a display-specific matter and should be addressed in display calibration software. It is essentially a form of tone mapping that deals with the inability of a display to reproduce the darkest coded shades.

**Comment by dzung-hoang** [comment]
I think we can agree that the different standards have different levels for reference white and reference black.

One question I have is "Are these differences accounted for in the conversion to and from linear RGB?" In other words, are reference white in sRGB and reference white in BT.709 converted to the same linear RGB value, given that the color space is the same?

Another question is "What is the scale of the linear RGB values?" Does 1.0 luminance (computed from linear R,G,B) correspond to 100 cd/m<sup>2</sup>?

**Comment by sekrit-twc** [comment]
For any relative transfer function, the maximum diffuse white value always maps to 1.0 in linear light (and 1.0 in nonlinear light). The peak luminance level is used only when converting to/from ST.2084, to map the relative scale into absolute light. Assuming a full-range 8-bit input signal, the coded value 255 always maps to 1.0 linear light in any SDR transfer function. In STD-B67, the halfway coded value always maps to 1.0. Outside of conversions involving ST.2084, a luminance of 1.0 has no physical meaning.

**Comment by dzung-hoang** [comment]
Thanks for answering my questions. I am closing this issue.
