### ISSUE TITLE
Usage question - mask

### ISSUE THREAD

**Issue by philrosenberg** [sekrit-twc/zimg#67]
Hi
I am learning how to use the zimg library by following the example. However I cannot quite work out what the count and mask variables are in the allocate_buffer function in api_example.cpp. Would it be possible for you to explain their contents and usage?

All the best

Phil

**Comment by sekrit-twc** [comment]
z.lib is capable of operating on images that are not fully allocated in memory. Instead, it is possible to load image scanlines on-the-fly into an image buffer holding a power-of-two number of scanlines. See the API documentation for `zimg_image_buffer` for more information. If you are only interested in full image buffers, you do not need to deal with buffer masks (set the mask to ZIMG_BUFFER_MAX, which is an all-ones bit pattern).

**Comment by philrosenberg** [comment]
Thanks for the reply
I guess there isn't an actual documentation document produced by the build, at least with Visual Studio (I couldn't see a doc build target in the makefile for a Linux build though - sorry if I am missing something). But thanks to your response I have located the appropriate comments in the header. Thanks for the help.

Phil
