### ISSUE TITLE
10 or 12 bit output

### ISSUE THREAD

**Issue by philrosenberg** [sekrit-twc/zimg#68]
Hi
Is it possible to generate 10 or 12 bit output with Zimg?

The options for zimgxx::zimage_format::pixel_type seem to indicate that 8/16 bit integer and 16/32 bit floating point output is possible, but I couldn't see anything regarding 10 or 12 bit.

Phil

**Comment by dzung-hoang** [comment]
Within zimg_img_format, set pixel_type to ZIMG_PIXEL_WORD and depth to 10 or 12.
