### ISSUE TITLE
Implement ICtCp color space per BT.2100

### ISSUE THREAD

**Issue by dzung-hoang** [sekrit-twc/zimg#69]
BT.2100 defines a new color space ICtCp. I can help add support for this to zimg.

**Comment by sekrit-twc** [comment]
Patches welcome. Is there an enumerated value for this system (matrix_coefficients)?

**Comment by dzung-hoang** [comment]
It's a multi-step process. Convert RGB to LMS then do PQ. Then matrix. It's spelled out in BT.2100.

Regards,
Dzung Hoang

**Comment by sekrit-twc** [comment]
I mean for the standard colorspace triplet (matrix-transfer-primaries). Has a code value been specified by ITU/MPEG?

As for the details of ICtCp, I see that the transfer characteristics can be either PG or HLG.

**Comment by dzung-hoang** [comment]
The JCT-VC is preparing draft text to add ICtCp support in HEVC.
http://phenix.int-evry.fr/jct/doc_end_user/documents/25_Chengdu/wg11/JCTVC-Y1003-v1.zip

There is no assigned triplet for ICtCp. The matrix_coeffs syntax element value is 14 for ICtCp color space which is specified by equations (E-62) to (E-64). The transfer function can be PQ (transfer_characteristics = 16) or HLG (transfer_characteristics = 18), but the HEVC spec does not limit ICtCp to these two transfer functions.

**Comment by sekrit-twc** [comment]
If a matrix_coeffs value has been reserved, that is sufficient. The constants described in BT.2100 appear to be specific to the Rec.2020 primaries. Is there a generalization?

**Comment by dzung-hoang** [comment]
ICtCp was designed with Rec.2020 colorimetry in mind. It is possible, but unlikely, that ICtCp will be used with another colorimetry.

**Comment by dzung-hoang** [comment]
I finished coding and am testing.

**Comment by dzung-hoang** [comment]
I just checked in my code changes. Please review and post comments here.

https://github.com/dzung-hoang/zimg

**Comment by sekrit-twc** [comment]
Can you upload a ICtCp test image with reference RGB image? I have left my remarks on your commit.

**Comment by dzung-hoang** [comment]
I updated the code per your comments.

https://github.com/dzung-hoang/zimg/commit/aa29d54e1a7ab5b6be7cfb0f33954e3fbf06b52b

I am working on generating ICtCp test image using HDRConvert used by JCT-VC/JVET.

**Comment by dzung-hoang** [comment]
unit test pushed

https://github.com/dzung-hoang/zimg/commit/a4b34069f569d9d98d41e438c03535c0b80bb9ef

**Comment by sekrit-twc** [comment]
Once you upload the ICtCp test image, I can begin verification and merging.

PLEASE NOTE: You must agree to either assign copyright of code to the project owner or license contributions under WTFPL (see COPYING).

**Comment by dzung-hoang** [comment]
I agree to WTFPL.

Regarding the ICtCp test image, I have a question on the image file format. I used testapp for my own testing and came across a limitation in the file format. This line of code in colorspaceapp.cpp colorspace_main() is a concern for me.

`		ImageFrame src_frame = imageframe::read(args.inpath, "i444s", args.width, args.height, zimg::PixelType::FLOAT, !!args.fullrange_in);
`
When studying the code, it looks to me like this read function overrides the pixel type in the format specification with FLOAT. Why do you not allow other values of PixelType?

**Comment by sekrit-twc** [comment]
The colorspaceapp is only for testing the colorspace module, which works in float. The depthapp can generate floating-point images for use with colorspaceapp. You can upload the test image in any format you like, e.g. 10/16-bit yuv dump, BMP, etc.

**Comment by sekrit-twc** [comment]
Any updates?

**Comment by dzung-hoang** [comment]
I have been busy at work and am traveling. The difficulty I'm having is that I cannot find any coded content with ICtCp colorspace.

I thought I could use HDRtools from 

https://gitlab.com/standards/HDRTools

but I don't trust it and need further study to verify that it works with ICtCp.


Regards,
Dzung Hoang

**Comment by dzung-hoang** [comment]
I finished testing on an SDR image and an HDR image. The files are attached.

[test_images.zip](https://github.com/sekrit-twc/zimg/files/923404/test_images.zip)

**Comment by sekrit-twc** [comment]
I tried to verify the code with your EXR images, but when I convert 'cosmos_2048x858_ictcp' to RGB as such:

`testapp.exe colorspace -w 2048 -h 858 --visualise x.bmp i444h@cosmos_2048x858_ictcp_rgbph.bin rgbph@test.bin ictcp:st_2084:2020 rgb:st_2084:2020`

The output image is all white pixels. I inspected the contents of the ICtCp EXR, and it appears all Y pixel values are near 1.0, which would be unusual for ST.2084. Can you explain what colorspaces the images you provided are in?

**Comment by dzung-hoang** [comment]
BT.2100 assumes that the R/G/B value of 1.0 corresponds to 10000 nits. Also, the floating point representation assumes full-range samples. Therefore you need to specify the following options: "--fullrange-in --fullrange-out --peak-luminance=10000"

The cosmos image is an image taken from Cosmos Laundromat and remastered in HDR by Netflix.

https://gooseberry.blender.org/

The color square is a sRGB image, and you need to set "--peak-luminance=100."

I am attaching the script I used for testing.
[test_cosmos.zip](https://github.com/sekrit-twc/zimg/files/924637/test_cosmos.zip)

**Comment by sekrit-twc** [comment]
Thank you for the update. I was able to verify that the conversion from ICtCp to RGB matched the reference image with '--peak-luminance=10000'.

Can you comment on the numerical issues I mentioned in my edit? I reproduced the steps used in the pipeline as a unit test and observed severe error in the green channel for certain test vectors. The attached code can be used to inspect the issue in a debugger.

https://pastebin.com/XAKPnzpb

You can also observe these issues if you attempt to round-trip the color square, storing the intermediate result in half-precision (EXR).

**Comment by dzung-hoang** [comment]
I am in the process of implementing a DoubleToHalf conversion in Excel VBA to try to find a stable matrix.

**Comment by sekrit-twc** [comment]
I have not done this investigation yet, but it may be necessary to use gaussian solvers (e.g. sgesv) instead of an inverse matrix. From what I can tell, an LU solution requires no more FLOPs (9 muls) than a matrix-vector product in the 3x3 case.

**Comment by dzung-hoang** [comment]
I am looking into the effect of rounding modes when converting from float to half-float. Hopefully this can give a simpler solution.

**Comment by sekrit-twc** [comment]
Do the standards or reference software provide any guidance on decoding ICtCp? On my end, I tried several approaches, but none of them were able to eliminate the problem. In fact, I noticed the issue can also be reproduced with the test vector (R=0, G=1.0, B=0). Even without any quantization of the intermediate result, this vector comes out as (R=0.09, G=1.0, B=0.014).

Part of the issue appears to be the dynamic range of the ST.2084 function, as even 1E-5 absolute error near zero in the linear domain maps to 0.1 in the transformed domain.

**Comment by sekrit-twc** [comment]
I just realized the aforementioned error would be invisible in PQ domain, since 1E-5 linear is 0.1 nits and 1.0 linear is 10000 nits. Perhaps there is no issue.

**Comment by dzung-hoang** [comment]
I cannot reproduce your result for RGB=[0,1,0]. See the attached spreadsheet. One round trip with 10-bit quantization of ICtCp gives me the reconstructed RGB=[-0.0039, 0.997691, -5.93973E-05].

[ICtCp_Worksheet.zip](https://github.com/sekrit-twc/zimg/files/931816/ICtCp_Worksheet.zip)

**Comment by sekrit-twc** [comment]
The discrepancy appears to be that you are using linear RGB values, but I am using R'G'B'.

**Comment by dzung-hoang** [comment]
I updated the spreadsheet to fix the quantization function to reflect A.2 in SMPTE-2084-2014, and also to allow selecting the bit-depth.

[ICtCp_Matrix.zip](https://github.com/sekrit-twc/zimg/files/945043/ICtCp_Matrix.zip)

Not surprisingly, the accuracy depends upon the selected bit-depth. Bit-depth of 11 seems to be the sweet spot for preserving the primary colors after clipping.

For each bit-depth, we can tweak the LMS-to-RGB matrix to get exact round-trip of the primary colors. I'll attempt that next.

**Comment by dzung-hoang** [comment]
It was easier than I thought to derive a LMS-to-RGB matrix to get exact round-trip of the primary colors. We basically just compute round-trip LMS of the identity RGB matrix, and then compute the matrix inverse of the round-trip LMS. See the attached spreadsheet.

[ICtCp_Matrix_v2.zip](https://github.com/sekrit-twc/zimg/files/945118/ICtCp_Matrix_v2.zip)

**Comment by sekrit-twc** [comment]
That method only accounts for errors caused by quantization, but in a real workflow, numerical errors can come from many sources, particularly data compression. Consider this scenario:

(1) Movie in R'G'B' received from distributor or studio.
(2) Movie is converted to HDR10+/ICtCp and compressed with HEVC Main 10
(3) Movie is converted back to R'G'B' at display interface.

The general principle that should hold is that errors in ICtCp should result in proportional errors in RGB.

**Comment by dzung-hoang** [comment]
I would disagree with the proportional RGB error metric. The right metric should be perceptual-based. The attached document set has a good treatment of compression errors of IPT-PQ (ICtCp with SMPTE-2084 PQ) compared to Y'CbCr.

[m37266-v2-m37266_IPTPQ_v2.zip](https://github.com/sekrit-twc/zimg/files/945523/m37266-v2-m37266_IPTPQ_v2.zip)

**Comment by sekrit-twc** [comment]
I agree that dE2000 is a better measure than RGB per-channel error. Can you provide a reference for computing dE2000 of HDR values? There are only 2^30 code points in 10-bit PQ space, so it should be possible to exhaustively test the conversion error.

**Comment by dzung-hoang** [comment]
This has a DeltaE computation module.

https://gitlab.com/standards/HDRTools

Look for DistortionMetricDeltaE.cpp.

**Comment by sekrit-twc** [comment]
I noticed that I was using the float-int cast in my quantization function, which was increasing the error considerably. After I applied correct rounding, I am seeing dE2000 of ~0.05 for (R=0,G=1,B=0) with 10-bit quantization and ~0.1 for (R=0,G=1,B=1). (R=0,G=1,B=1) appears to be the worst-case input. The simple YCbCr system has dE2000 of ~0.03 and ~0.01, respectively. The error appears to be stable and does not increase significantly with additional round-trips. Is this a reasonable result?

**Comment by dzung-hoang** [comment]
That seems even better than published results.

**Comment by sekrit-twc** [comment]
I will need to investigate again to ensure I am measuring dE correctly.

**Comment by sekrit-twc** [comment]
I did an exhaustive analysis and found that the overall dE was not worse than NCL for ICtCp as implemented in the commit.

**Comment by dzung-hoang** [comment]
Since one of the aims of ICtCp is to improve color gamut mapping, I suggest you allow ICtCp to be used with any gamut and not just BT.2020. I will use zimg for color gamut mapping experiments and I'm sure others would too if this restriction were removed.

**Comment by sekrit-twc** [comment]
That would require a different RGB-LMS matrix, would it not? I noticed the document in m37266-v2-m37266_IPTPQ_v2.zip proposed for LMS to be a value of color_primaries, but that appears to not have been accepted by JCT-VC.

**Comment by dzung-hoang** [comment]
Now that I think about it, generating ICtCp output with a different input color primaries is already supported by zimg. The input color primaries are first converted to BT.2020 and then ICtCp conversion is performed. The challenge for color gamut mapping is to figure out how to manipulate the ICtCp color space to reduce or expand the color volume. Then the inverse conversion is performed from ICtCp to linear BT.2020 RGB and then to the target color primaries.

**Comment by ValZapod** [comment]
@sekrit-twc Can you help us with ICtCp in ffmpeg? Please?https://trac.ffmpeg.org/ticket/7624
Dolby vision with ICtCp is being presented incorrectly.

**Comment by sekrit-twc** [comment]
@ValZapod I do not understand. Is there some action required from z.lib here?

**Comment by ValZapod** [comment]
@sekrit-twc Well, it is not working by default. (( And this is how it looks: https://github.com/HandBrake/HandBrake/issues/1728#issuecomment-448015493

Please?)))

**Comment by ValZapod** [comment]
@sekrit-twc I forgot to give you an issue in trac. https://trac.ffmpeg.org/ticket/7624
Also that file .ts with ICtCp. https://drive.google.com/file/d/1aP276spsqW-EbIIVrzdI9mwTYO87d0ac/view?usp=sharing

**Comment by wm4** [comment]
That's a problem with ffmpeg or ffmpeg's zimg wrapper (I assume you mean using zimg through ffmpeg's zscale filter).

I tried that sample, and ffmpeg returns "unspecified" for all relevant colorspace parameters. Is that file even valid?

**Comment by ValZapod** [comment]
@sekrit-twc What does it mean valid? Did you try to open it in VLC? It is good but for the color. It is just hevc in TS. (Though this hevc is called dvhe and it has dolby vision layer in NAL unit 62 and 63 (see https://trac.ffmpeg.org/ticket/5688) -- but this is not really important, this data can be skipped.)

**Comment by dzung-hoang** [comment]
@ValZapod
Dolby Vision uses the IPT colorspace, which is different from ICtCp. See [Here](https://diversifiedvideosolutions.com/dolby_vision.html) and [Here](https://www.dolby.com/us/en/technologies/dolby-vision/ICtCp-white-paper.pdf). IMHO, supporting IPT should be a feature request. However, given that IPT is Dolby-proprietary and is likely to be covered by patents, this decision should be made after careful deliberation.

**Comment by sekrit-twc** [comment]
Hello again, @dzung-hoang . Is there any information about the IPT colorspace? The linked document only states that "proprietary IPT [is] similar to BT.2100 ICtCp."

**Comment by dzung-hoang** [comment]
@sekrit-twc, there is some technical detail in the linked Dolby white paper.

**Comment by sekrit-twc** [comment]
I found the information on page 7.

[I P T] = [[0.4 0.2 0.2] [4.4550-4.85100.3960] [0.80560.3572-1.1628]] * [L M S]
Rotation = [[1 0 0] [0 0.4226 -0.9063] [0 0.9063 0.4226]]
Scalar = [[1 1 1] [1.4 1.4 1.4] [1 1 1]]

Is the takeaway that IPT differs from ICtCp in the matrix coefficients step, using the product of the aforementioned three matrices instead of the LMS-ICtCp matrix?

**Comment by dzung-hoang** [comment]
No, the page shows the derivation of ICtCp from IPT. If you were to apply all three matrix multiplies, you would end up with ICtCp.
This info is really background information on how ICtCp was derived from IPT. The exact details are in confidential Dolby Vision documents, which I have not seen. I suppose some more digging around might reveal a public source. I would dig into JVET and JCT-VC documents where Dolby made presentations on IPT and ICtCp. I would also check HDRConvert on github. This is the software JVET and JCT-VC uses to convert different color formats.

Sent from Yahoo Mail for iPhone


On Sunday, November 10, 2019, 1:29 PM, sekrit-twc <notifications@github.com> wrote:


I found the information on page 7.

[I P T] = [[0.4 0.2 0.2] [4.4550-4.85100.3960] [0.80560.3572-1.1628]] * [L M S]
Rotation = [[1 0 0] [0 0.4226 -0.9063] [0 0.9063 0.4226]]
Scalar = [[1 1 1] [1.4 1.4 1.4] [1 1 1]]

Is the takeaway that IPT differs from ICtCp in the matrix coefficients step, using the product of the aforementioned three matrices instead of the LMS-ICtCp matrix?

**Comment by ValZapod** [comment]
@sekrit-twc Mmm. First, there is a file "03. Color Bars BT2020 50%_Blue Filter_Dolby_Vision.mp4" in
https://diversifiedvideosolutions.com/UHD_Project/Dolby_Vision_Test_Pattern_Demo.zip
which can be used to check if it is really just ICtCp or there are some modifications. Right?
And anyway as of now I think VLC (and ffplay and ffmpeg) just does normal BT.2020 conversion, am I right? It can still be better if it used BT.2100 ICtCp.

**Comment by dzung-hoang** [comment]
> I found the information on page 7.
> 
> [I P T] = [[0.4 0.2 0.2] [4.4550 -4.8510 0.3960] [0.8056 0.3572 -1.1628]] * [L M S]
> Rotation = [[1 0 0] [0 0.4226 -0.9063] [0 0.9063 0.4226]]
> Scalar = [[1 1 1] [1.4 1.4 1.4] [1 1 1]]
> 
> Is the takeaway that IPT differs from ICtCp in the matrix coefficients step, using the product of the aforementioned three matrices instead of the LMS-ICtCp matrix?

There is a typo in your L'M'S' to IPT conversion matrix.  As I already replied, Rotation and Scaler conversions are there to convert IPT to ICtCp.

The following link confirms the above conversion matrix. https://gitlab.com/standards/HDRTools/blob/master/common/src/ToneMappingBT2390IPT.cpp

This should be sufficient information to add support for IPT.

**Comment by ValZapod** [comment]
@dzung-hoang IPT as finally the one in Dolby Vision? Or this is still not enough?

**Comment by ValZapod** [comment]
Are those https://github.com/testing-av/testing-video/blob/9256b779f7721bd3dbdceedab7c65b6f64bbab79/core/src/main/java/band/full/video/dolby/VdrDmDataPayload.java#L42 correct IPTPQc2 og Dolby Vision profile 5 coefficients?

```
/** IPT to LMS */
    public static final short[] IPTPQ_YCCtoRGB_coef = {
        8192, 799, 1681, // 1.0,
        8192, -933, 1091, // 1.0,
        8192, 267, -5545, // 1.0,
    };

    /** IPT to LMS */
    public static final long[] IPTPQ_YCCtoRGB_offset = {
        0, 134217728, 134217728 // 0, 0.5, 0.5
    };

    /** LMS inverse cross-talk matrix for c == 0.02 */
    public static final short[] IPTPQc2_RGBtoLMS_coef = {
        17081, -349, -349,
        -349, 17081, -349,
        -349, -349, 17081,
    };
```

**Comment by ValZapod** [comment]
Guys, I (well, [not I](https://code.videolan.org/videolan/libplacebo/-/issues/72)) found this [ITU-T H Suppl. 18](https://www.itu.int/ITU-T/recommendations/rec.aspx?id=13441&lang=en) document that specifies two "inverted" matrixes for ICtCp with 15 decimal places. I then found out that those matrixes are just https://www.wolframalpha.com/input/?i=Inverse%5BSetPrecision%5B%7B%7B2048%2F4096.%2C+2048%2F4096.%2C+0%7D%2C+%7B6610%2F4096.%2C+-13613%2F4096.%2C7003%2F4096.%7D%2C+%7B17933%2F4096.%2C+-17390%2F4096.%2C+-543%2F4096.%7D%7D%2C+30%5D%5D and that you can get **in integers** matrixes https://www.wolframalpha.com/input/?i=Inverse%5BSetPrecision%5B%7B%7B2048%2F4096.%2C+2048%2F4096.%2C+0%7D%2C+%7B6610%2F4096.%2C+-13613%2F4096.%2C7003%2F4096.%7D%2C+%7B17933%2F4096.%2C+-17390%2F4096.%2C+-543%2F4096.%7D%7D%2C+Inf%5D%5D
