### ISSUE TITLE
zimg 2.5.1 win32 build error

### ISSUE THREAD

**Issue by fuchanghao** [sekrit-twc/zimg#70]
x64 build works fine but win32 fails.

I tried re-install it but happenes the same.

visual studio 2017 
Windows sdk 10.0.15063.0

error message

> 1>d:\source code\vapoursynth\zimg\src\zimg\colorspace\operation_impl_sse.cpp : fatal error C1001: 编译器中发生内部错误。
> 1>(编译器文件“f:\dd\vctools\compiler\utc\src\p2\main.c”，第 255 行)
> 1> 要解决此问题，请尝试简化或更改上面所列位置附近的程序。
> 1>请选择 Visual C++
> 1>“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息。
> 1>d:\source code\vapoursynth\zimg\src\zimg\colorspace\operation_impl_sse.cpp : fatal error C1001: 编译器中发生内部错误。
> 1>(编译器文件“f:\dd\vctools\compiler\utc\src\p2\main.c”，第 255 行)
> 1> 要解决此问题，请尝试简化或更改上面所列位置附近的程序。
> 1>请选择 Visual C++
> 1>“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息。
> 1>
> 1>LINK : fatal error LNK1000: Internal error during IMAGE::BuildImage
> 1>
> 1>  Version 14.10.25019.0
> 1>
> 1>  ExceptionCode            = C0000005
> 1>  ExceptionFlags           = 00000000
> 1>  ExceptionAddress         = 50CF2A8C (50C80000) "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\c2.dll"
> 1>  NumberParameters         = 00000002
> 1>  ExceptionInformation[ 0] = 00000000
> 1>  ExceptionInformation[ 1] = 00000004
> 1>
> 1>CONTEXT:
> 1>  Eax    = 00000000  Esp    = 00D3E5B8
> 1>  Ebx    = 00000000  Ebp    = 00D3E5D0
> 1>  Ecx    = 00000000  Esi    = 00000000
> 1>  Edx    = 00001020  Edi    = 06555A1C
> 1>  Eip    = 50CF2A8C  EFlags = 00010246
> 1>  SegCs  = 00000023  SegDs  = 0000002B
> 1>  SegSs  = 0000002B  SegEs  = 0000002B
> 1>  SegFs  = 00000053  SegGs  = 0000002B
> 1>  Dr0    = 00000000  Dr3    = 00000000
> 1>  Dr1    = 00000000  Dr6    = 00000000
> 1>  Dr2    = 00000000  Dr7    = 00000000

**Comment by sekrit-twc** [comment]
I cannot reproduce this. I checked out the 'v2.5.1' tag, set the SDK version to '10.0.15063.0' and did a clean build.

**Comment by fuchanghao** [comment]
can you test build with vapoursynth leatest git?

**Comment by fuchanghao** [comment]
OK I see.

I will try another computer to see what happened.
