### ISSUE TITLE
Illegal instruction on g++ -O2 build(Windows)

### ISSUE THREAD

**Issue by kanryu** [sekrit-twc/zimg#72]
Hi all,

I build zimg with VisualStudio2015 and gcc-6.0.3 on MinGW64.
This problem is only gcc with -O2 not -O0 
VisualStudio2015 is no problem.

the program stops in graph.process()

https://gist.github.com/kanryu/e324f2cb4b36c306d58a16c2479b5550

CXXFLAGS = -O2 -MD -MP -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers  -msse -msse2 -mavx -mavx2 -mf16c -mfma -fvisibility=hidden
LDFLAGS += -O2 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -msse -msse2 -mavx -mavx2 -mf16c -mfma -fvisibility=hidden

the zimg is release-2.5.
release-.2.5.1, I can't build on VisualStudio2015.

At last, there is no problem testapp/api-example on autoconf/configure .

comments?

**Comment by sekrit-twc** [comment]
The subject of your gist is "Illegal instruction on g++ -O2 build." Does your CPU actually support all the instruction sets you requested? Can you provide a backtrace?

**Comment by kanryu** [comment]
Thanks.

I put a backtrace on the gist.
To see.

**Comment by sekrit-twc** [comment]
Can you provide a disassembly of 'zimg::depth::ordered_dither_b2w_sse2'? It looks like your CXXFLAGS caused the program to require AVX2 (i.e. Haswell or later). Please use the GNU Autotools build system to compile z.lib.

**Comment by kanryu** [comment]
> Please use the GNU Autotools build system to compile z.lib.
I tried to build with setting -mCPUx flags for each impl_XXX.cpp .

detail: https://github.com/kanryu/quickviewer/blob/master/zimg/zimg.pro

so now run correctly.
Thanks!
