### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [sekrit-twc/zimg#86]
Based on https://github.com/sekrit-twc/zimg/releases and https://github.com/sekrit-twc/zimg/releases/latest I cannot tell if 2.6.1 or 2.6.2 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by sekrit-twc** [comment]
2.6.2

**Comment by ilovezfs** [comment]
@sekrit-twc thanks! Voilà https://github.com/Homebrew/homebrew-core/pull/20627
