### ISSUE TITLE
problem with HDR conversion as input

### ISSUE THREAD

**Issue by kodabb** [sekrit-twc/zimg#87]
Hi,
when converting and HDR video using master, the colors look all wrong depending on the desired output conversion. From the look of it there is something off with the strides or alignment.

`stmpe2084 -> smpte2084`
![screenshot 2017-11-15 16 49 05](https://user-images.githubusercontent.com/1374357/32905591-59e52920-cac8-11e7-86cb-1b5b754d30ef.png)

`smpte2084 -> bt2020`
![screenshot 2017-11-15 16 49 33](https://user-images.githubusercontent.com/1374357/32905609-6a1223ca-cac8-11e7-94c0-1be82ab1b1cb.png)

`smpte2084 -> bt709`
this one works fine

the last hash that worked for me was ec1e2a9ccd3a7dce2c50f8d7005f7a5b56928ff8

**Comment by sekrit-twc** [comment]
Does d1e0cca also not work?

**Comment by sekrit-twc** [comment]
Rather, it should be fixed now. It was incorrectly reading the first plane for all channels.

**Comment by kodabb** [comment]
Something changed in the tree history, the broken commit for me was 86951bead48d03bd90110933d7b02f8bbf4b10d9 but that hash is not present any more

At any rate, I tested again in current master (eaa427f7efde97af0312fa48c8b0b7678743e648) and it works as expected. Thank you
