### ISSUE TITLE
How to run zimg on multithread?

### ISSUE THREAD

**Issue by kanryu** [sekrit-twc/zimg#88]
Hi,

I want to run zimg with multithread.
I have read a sample, 'zimg/src/testapp/graphapp.cpp', but I can't understand.

Could you explain the procedure for parallel processing into an image with zimg in multithread?

**Comment by sekrit-twc** [comment]
You can process multiple images with the same graph on different threads. You can also process a single image by dividing it into tiles, if it is sufficiently large.

**Comment by kanryu** [comment]
Thank you.
I want to process a single image by diving into tiles, and work with multithread.

**Comment by sekrit-twc** [comment]
Hi, you can do this by dividing the output image into tiled regions (1 per thread) and then creating a separate graph for each region. For example, if the input dimension is 512x512 and the output dimension is 1024x1024, the output can be processed as four 256x256->512x512 transforms. Using `zimg_image_format::active_region`, you can specify these logical 256x256 inputs.

    double src_tile_w = src_width * ((double)src_width / (double)dst_width);
    double src_tile_h = src_height * ((double)src_height / (double)dst_height);
    /* When calling zimg_filter_graph_process, set the image buffer to point to the desired region,
       or perform an on-the-fly copy with a callback. */
    zimg_image_format dst_format;
    dst_format.width = dst_width / 2;
    dst_format.height = dst_height / 2;
    /* tile0 */
    zimg_image_format src_format;
    src_format.active_region.left = 0 * src_tile_w;
    src_format.active_region.top = 0 * src_tile_h;
    src_format.active_region.width = src_tile_w;
    src_format.active_region.height = src_tile_h;
    /* tile1 */
    src_format.active_region.left = 1 * src_tile_w;
    src_format.active_region.top = 0 * src_tile_h;
    /* tile 2 */
    src_format.active_region.left = 0 * src_tile_w;
    src_format.active_region.top = 1 * src_tile_h;
    /* tile3 */
    src_format.active_region.left = 1 * src_tile_w;
    src_format.active_region.top = 1 * src_tile_h;

It is left as an exercise to the reader how to handle the case where the input/output image size is not cleanly divisible.

**Comment by kanryu** [comment]
Thanks!
I test adobe later, and I will report this.

**Comment by sekrit-twc** [comment]
@kanryu I added a code example for tiled threading in doc/example. From my testing, it is only worth it for very large images, because of the startup overhead. I also found an issue when using `active_region` together with an unpack callback. If you use unpack callbacks, you should use only vertical (columnar) tiles.

**Comment by kanryu** [comment]
thanks!
