### ISSUE TITLE
pixel format alpha conversion

### ISSUE THREAD

**Issue by kodabb** [sekrit-twc/zimg#90]
Hi,
I'm trying to convert a YUVA 4444 buffer of type `PixelType::FLOAT` to a YUV 420 10bit one of type `PixelType::WORD`, however the library fails with a `BitDepthOverflow` exception during the graph construction phase.
Debugging only lead to the message at line 138 of `graphbuilder.cpp`, in which `state.depth` correctly reports `32` and `pixel_depth(state.type)` reports `16`.

I would expect that the library would be able to either dither or clip the alpha plane and proceed as normal. Is it something not supported or should I do something before setting up the buffers?
Thank you

**Comment by sekrit-twc** [comment]
Are you sure you set the input type to FLOAT? This error sounds like you incorrectly set the source pixel type to WORD.

**Comment by kodabb** [comment]
yeah I'm sure, I added
`fprintf(stderr, "pixel_type %d - depth %d\n", format->pixel_type,  format->depth);`
to my code and I correctly get
```
source - pixel_type 1 - depth 10
destination - pixel_type 3 - depth 32
```

This is helpful, I thought the problem was in the yuva4444_float->yuv420_10 but this happens on the yuva4444_10 -> yuva4444_float instead. For full explanation of my pipeline, I'm converting YUVA444_10bit to YUVA444_float and then to YUV444_10bit.

**Comment by sekrit-twc** [comment]
Please dump the contents of the input and output formats so I can reproduce.

**Comment by kodabb** [comment]
You were right, the error was in my code and it was exactly as you described, thanks to your tip I was able to fix it.
We can close this one, thanks again!
