### ISSUE TITLE
Feature request: allow for user provided LUTs in color transfer functions

### ISSUE THREAD

**Issue by markniebur** [sekrit-twc/zimg#93]
I am working on a project for my company where one of the requirements is using a LUT to perform the transform from HLG to HDR10.  I am trying to gauge interest from the current maintainers to see if you would consider a PR that provides such functionality.

**Comment by sekrit-twc** [comment]
Is it a 3DLUT? You can use the TimeCube application to apply those.

**Comment by markniebur** [comment]
Ok, I hadn't found that application in my search, thank you for pointing me there.  I will work on using that instead.
