### ISSUE TITLE
yuv410 - image dimensions must be divisible by subsampling factor

### ISSUE THREAD

**Issue by kodabb** [sekrit-twc/zimg#94]
Hi
I've had this kind of failure when encoding a video. Interestingly enough this failure happens even if there is not any scaling operation involved.

1. generate the file - `./ffmpeg -f lavfi -i testsrc -s 190x240 -t 1 -pix_fmt yuv410p -c:v ffv1  output-yuv410p.avi`
2. encode with `./ffmpeg -i output-yuv410p.avi -vf zscale output.mp4`

result `code 1027: image dimensions must be divisible by subsampling factor`

**Comment by sekrit-twc** [comment]
yuv410p is 4x subsampled
190/4 = 47.5

The format fails the validation check.
