### ISSUE TITLE
OSI-approved license

### ISSUE THREAD

**Issue by jan-wassenberg** [sekrit-twc/zimg#97]
Hi, this project looks great! Very impressed to see SIMD and support for BT.2100.

Unfortunately there is a difficulty with the WTFPL, so I can't use the code :/
(The license is not legally sound and possibly invalid in Europe.)

Would it be possible to dual-license under an approved OSI-license?

I think Unlicense would come close to the intention of the current license,
allowing any use while also protecting your project from any liability claims.

Alternative: MIT is widely used, also protects you and only adds a
requirement to keep the copyright/permission notices intact.

**Comment by sekrit-twc** [comment]
Hello. This was discussed within the z.lib community, and it was determined that any relicense would derive its legitimacy from the implied compatibility with WTFPL.

**Comment by jan-wassenberg** [comment]
Hi, thank you for discussing it.

Unlicense does seem to be compatible with WTFPL, except that it does not allow users to claim damages from the authors.

**Comment by sekrit-twc** [comment]
Since any relicense could only ever apply to new commits, the implication is that the existing code base would continue to fall under WTFPL. Thus, any restrictions or rights provided by a new license would be legitimate only as far as they are compatible with WTFPL.

**Comment by jan-wassenberg** [comment]
Thank you for clarifying! I understand.
Yes, an (incompatible) relicensing typically involves all past contributors agreeing to the new license, which is difficult.
Shall we close the issue?
