### ISSUE TITLE
[Question] v210 support

### ISSUE THREAD

**Issue by Auliyaa** [sekrit-twc/zimg#98]
Hi,

Seems like this question has not been asked yet, I'd like to know if zimg supports V210 buffer packing format as inpu and if there is some related example code somewhere that could demonstrate this.

Regards

**Comment by sekrit-twc** [comment]
The API only accepts planar inputs. You can convert packed to planar on-the-fly to avoid a frame copy (see: api_example.cpp for a RGB example).
